package net.averageanime.createfood.item;

import java.util.HashMap;
import java.util.Map;

/**
 * Built-in ingredient tooltip data for all CreateFood items that have tips() defined
 * in the 1.21.1 ItemRegistry. Keyed by item id path (no namespace).
 *
 * Value format: String array where
 *   [0] = compatibility/mod translation key (null if none)
 *   [1..] = full tooltip.createfood.* ingredient translation keys
 */
public final class BuiltinTooltips {

    private BuiltinTooltips() {}

    public static final Map<String, String[]> TIPS = new HashMap<>();

    static {
        TIPS.put("cloth_filter_pressed_cocoa", new String[]{null, "tooltip.createfood.pressed_cocoa_ingredient"});
        TIPS.put("cloth_filter_egg_yolk", new String[]{null, "tooltip.createfood.egg_yolk_ingredient"});
        TIPS.put("cloth_filter_egg", new String[]{null, "tooltip.createfood.egg_ingredient"});
        TIPS.put("cloth_filter_cacao_mass", new String[]{null, "tooltip.createfood.cacao_mass_ingredient"});
        TIPS.put("apple_cream_cake_slice", new String[]{null, "tooltip.createfood.apple_cream_frosting_ingredient"});
        TIPS.put("apple_cream_chocolate", new String[]{null, "tooltip.createfood.apple_cream_frosting_ingredient"});
        TIPS.put("apple_cream_chocolate_cupcake", new String[]{null, "tooltip.createfood.apple_cream_frosting_ingredient"});
        TIPS.put("apple_cream_chocolate_donut", new String[]{null, "tooltip.createfood.apple_cream_frosting_ingredient"});
        TIPS.put("apple_cream_chocolate_pastry", new String[]{null, "tooltip.createfood.apple_cream_frosting_ingredient"});
        TIPS.put("apple_cream_chocolate_sweet_roll", new String[]{null, "tooltip.createfood.apple_cream_frosting_ingredient"});
        TIPS.put("apple_cream_cupcake", new String[]{null, "tooltip.createfood.apple_cream_frosting_ingredient"});
        TIPS.put("apple_cream_dark_chocolate", new String[]{null, "tooltip.createfood.apple_cream_frosting_ingredient"});
        TIPS.put("apple_cream_donut", new String[]{null, "tooltip.createfood.apple_cream_frosting_ingredient"});
        TIPS.put("apple_cream_frosting_piping_bag", new String[]{null, "tooltip.createfood.apple_cream_frosting_ingredient"});
        TIPS.put("apple_cream_mini_waffle", new String[]{null, "tooltip.createfood.apple_cream_frosting_ingredient"});
        TIPS.put("apple_cream_pastry", new String[]{null, "tooltip.createfood.apple_cream_frosting_ingredient"});
        TIPS.put("apple_cream_sweet_roll", new String[]{null, "tooltip.createfood.apple_cream_frosting_ingredient"});
        TIPS.put("apple_cream_white_chocolate", new String[]{null, "tooltip.createfood.apple_cream_frosting_ingredient"});
        TIPS.put("apple_ice_cream_sandwich", new String[]{null, "tooltip.createfood.apple_ice_cream_ingredient"});
        TIPS.put("apple_jam_chocolate_donut", new String[]{null, "tooltip.createfood.apple_jam_ingredient"});
        TIPS.put("apple_jam_donut", new String[]{null, "tooltip.createfood.apple_jam_ingredient"});
        TIPS.put("apple_jam_sandwich", new String[]{null, "tooltip.createfood.apple_jam_ingredient"});
        TIPS.put("bacon_calzone", new String[]{null, "tooltip.createfood.cheese_ingredient", "tooltip.createfood.bacon_ingredient"});
        TIPS.put("bacon_pizza_slice", new String[]{null, "tooltip.createfood.bacon_ingredient"});
        TIPS.put("bacon_sandwich", new String[]{null, "tooltip.createfood.bacon_ingredient"});
        TIPS.put("bacon_sandwich_lettuce", new String[]{null, "tooltip.createfood.bacon_ingredient", "tooltip.createfood.lettuce_ingredient"});
        TIPS.put("baked_potato_butter", new String[]{null, "tooltip.createfood.butter_ingredient"});
        TIPS.put("baked_potato_butter_bacon", new String[]{null, "tooltip.createfood.butter_ingredient", "tooltip.createfood.bacon_ingredient"});
        TIPS.put("baked_potato_butter_cheese", new String[]{null, "tooltip.createfood.butter_ingredient", "tooltip.createfood.cheese_ingredient"});
        TIPS.put("baked_potato_butter_fish", new String[]{null, "tooltip.createfood.butter_ingredient", "tooltip.createfood.fish_ingredient"});
        TIPS.put("baked_potato_butter_fried_egg", new String[]{null, "tooltip.createfood.butter_ingredient", "tooltip.createfood.fried_egg_ingredient"});
        TIPS.put("baked_potato_butter_mushroom", new String[]{null, "tooltip.createfood.butter_ingredient", "tooltip.createfood.mushroom_ingredient"});
        TIPS.put("baked_potato_butter_sour_cream", new String[]{null, "tooltip.createfood.butter_ingredient", "tooltip.createfood.sour_cream_ingredient"});
        TIPS.put("beef_bun_bacon", new String[]{null, "tooltip.createfood.bacon_ingredient"});
        TIPS.put("beef_bun_bacon_lettuce", new String[]{null, "tooltip.createfood.bacon_ingredient", "tooltip.createfood.lettuce_ingredient"});
        TIPS.put("beef_bun_bacon_lettuce_tomato", new String[]{null, "tooltip.createfood.bacon_ingredient", "tooltip.createfood.lettuce_ingredient", "tooltip.createfood.tomato_ingredient"});
        TIPS.put("beef_bun_cheese", new String[]{null, "tooltip.createfood.cheese_ingredient"});
        TIPS.put("beef_bun_cheese_bacon", new String[]{null, "tooltip.createfood.cheese_ingredient", "tooltip.createfood.bacon_ingredient"});
        TIPS.put("beef_bun_cheese_bacon_lettuce", new String[]{null, "tooltip.createfood.cheese_ingredient", "tooltip.createfood.bacon_ingredient", "tooltip.createfood.lettuce_ingredient"});
        TIPS.put("beef_bun_cheese_bacon_lettuce_tomato", new String[]{null, "tooltip.createfood.cheese_ingredient", "tooltip.createfood.bacon_ingredient", "tooltip.createfood.lettuce_ingredient", "tooltip.createfood.tomato_ingredient"});
        TIPS.put("beef_bun_cheese_lettuce", new String[]{null, "tooltip.createfood.cheese_ingredient", "tooltip.createfood.lettuce_ingredient"});
        TIPS.put("beef_bun_cheese_lettuce_tomato", new String[]{null, "tooltip.createfood.cheese_ingredient", "tooltip.createfood.lettuce_ingredient", "tooltip.createfood.tomato_ingredient"});
        TIPS.put("beef_bun_cheese_onion", new String[]{null, "tooltip.createfood.cheese_ingredient", "tooltip.createfood.onion_ingredient"});
        TIPS.put("beef_bun_cheese_onion_bacon", new String[]{null, "tooltip.createfood.cheese_ingredient", "tooltip.createfood.onion_ingredient", "tooltip.createfood.bacon_ingredient"});
        TIPS.put("beef_bun_cheese_onion_bacon_lettuce", new String[]{null, "tooltip.createfood.cheese_ingredient", "tooltip.createfood.onion_ingredient", "tooltip.createfood.bacon_ingredient", "tooltip.createfood.lettuce_ingredient"});
        TIPS.put("beef_bun_cheese_onion_lettuce", new String[]{null, "tooltip.createfood.cheese_ingredient", "tooltip.createfood.onion_ingredient", "tooltip.createfood.lettuce_ingredient"});
        TIPS.put("beef_bun_cheese_onion_lettuce_tomato", new String[]{null, "tooltip.createfood.cheese_ingredient", "tooltip.createfood.onion_ingredient", "tooltip.createfood.lettuce_ingredient", "tooltip.createfood.tomato_ingredient"});
        TIPS.put("beef_bun_cheese_tomato", new String[]{null, "tooltip.createfood.cheese_ingredient", "tooltip.createfood.tomato_ingredient"});
        TIPS.put("beef_bun_crimson_fungus", new String[]{null, "tooltip.createfood.crimson_fungus_ingredient"});
        TIPS.put("beef_bun_lettuce", new String[]{null, "tooltip.createfood.lettuce_ingredient"});
        TIPS.put("beef_bun_lettuce_tomato", new String[]{null, "tooltip.createfood.lettuce_ingredient", "tooltip.createfood.tomato_ingredient"});
        TIPS.put("beef_bun_onion", new String[]{null, "tooltip.createfood.onion_ingredient"});
        TIPS.put("beef_bun_onion_bacon", new String[]{null, "tooltip.createfood.onion_ingredient", "tooltip.createfood.bacon_ingredient"});
        TIPS.put("beef_bun_onion_bacon_lettuce", new String[]{null, "tooltip.createfood.onion_ingredient", "tooltip.createfood.bacon_ingredient", "tooltip.createfood.lettuce_ingredient"});
        TIPS.put("beef_bun_onion_lettuce", new String[]{null, "tooltip.createfood.onion_ingredient", "tooltip.createfood.lettuce_ingredient"});
        TIPS.put("beef_bun_onion_lettuce_tomato", new String[]{null, "tooltip.createfood.onion_ingredient", "tooltip.createfood.lettuce_ingredient", "tooltip.createfood.tomato_ingredient"});
        TIPS.put("beef_bun_peanut_butter", new String[]{"peanut_butter", "tooltip.createfood.peanut_butter_ingredient"});
        TIPS.put("beef_bun_peanut_butter_bacon", new String[]{"peanut_butter", "tooltip.createfood.peanut_butter_ingredient", "tooltip.createfood.bacon_ingredient"});
        TIPS.put("beef_bun_tomato", new String[]{null, "tooltip.createfood.tomato_ingredient"});
        TIPS.put("beef_bun_warped_fungus", new String[]{null, "tooltip.createfood.warped_fungus_ingredient"});
        TIPS.put("beef_burrito_rice", new String[]{null, "tooltip.createfood.beef_ingredient", "tooltip.createfood.rice_ingredient"});
        TIPS.put("beef_calzone", new String[]{null, "tooltip.createfood.cheese_ingredient", "tooltip.createfood.beef_ingredient"});
        TIPS.put("beef_meatball_sandwich", new String[]{null, "tooltip.createfood.beef_meatballs_ingredient"});
        TIPS.put("beef_rice_bowl", new String[]{null, "tooltip.createfood.kelp_ingredient"});
        TIPS.put("beef_taco", new String[]{null, "tooltip.createfood.beef_ingredient"});
        TIPS.put("beef_taco_lettuce", new String[]{null, "tooltip.createfood.beef_ingredient", "tooltip.createfood.lettuce_ingredient"});
        TIPS.put("beef_taco_lettuce_taco_sauce", new String[]{null, "tooltip.createfood.beef_ingredient", "tooltip.createfood.lettuce_ingredient", "tooltip.createfood.taco_sauce_ingredient"});
        TIPS.put("beef_wrap_lettuce_beetroot", new String[]{null, "tooltip.createfood.beef_ingredient", "tooltip.createfood.lettuce_ingredient", "tooltip.createfood.beetroot_ingredient"});
        TIPS.put("berry_cream_cake_slice", new String[]{null, "tooltip.createfood.berry_cream_frosting_ingredient"});
        TIPS.put("berry_cream_cake_slice_chorus_fruit", new String[]{null, "tooltip.createfood.berry_cream_frosting_ingredient", "tooltip.createfood.chorus_fruit_ingredient"});
        TIPS.put("berry_cream_cake_slice_glow_berry", new String[]{null, "tooltip.createfood.berry_cream_frosting_ingredient", "tooltip.createfood.glow_berry_ingredient"});
        TIPS.put("berry_cream_cake_slice_sweet_berry", new String[]{null, "tooltip.createfood.berry_cream_frosting_ingredient", "tooltip.createfood.berry_ingredient"});
        TIPS.put("berry_cream_chocolate", new String[]{null, "tooltip.createfood.berry_cream_frosting_ingredient"});
        TIPS.put("berry_cream_chocolate_cupcake", new String[]{null, "tooltip.createfood.berry_cream_frosting_ingredient"});
        TIPS.put("berry_cream_chocolate_donut", new String[]{null, "tooltip.createfood.berry_cream_frosting_ingredient"});
        TIPS.put("berry_cream_chocolate_pastry", new String[]{null, "tooltip.createfood.berry_cream_frosting_ingredient"});
        TIPS.put("berry_cream_chocolate_sweet_roll", new String[]{null, "tooltip.createfood.berry_cream_frosting_ingredient"});
        TIPS.put("berry_cream_chocolate_sweet_roll_sweet_berry", new String[]{null, "tooltip.createfood.berry_cream_frosting_ingredient", "tooltip.createfood.berry_ingredient"});
        TIPS.put("berry_cream_cupcake", new String[]{null, "tooltip.createfood.berry_cream_frosting_ingredient"});
        TIPS.put("berry_cream_dark_chocolate", new String[]{null, "tooltip.createfood.berry_cream_frosting_ingredient"});
        TIPS.put("berry_cream_donut", new String[]{null, "tooltip.createfood.berry_cream_frosting_ingredient"});
        TIPS.put("berry_cream_frosting_piping_bag", new String[]{null, "tooltip.createfood.berry_cream_frosting_ingredient"});
        TIPS.put("berry_cream_mini_waffle", new String[]{null, "tooltip.createfood.berry_cream_frosting_ingredient"});
        TIPS.put("berry_cream_mini_waffle_sweet_berry", new String[]{null, "tooltip.createfood.berry_cream_frosting_ingredient", "tooltip.createfood.berry_ingredient"});
        TIPS.put("berry_cream_pastry", new String[]{null, "tooltip.createfood.berry_cream_frosting_ingredient"});
        TIPS.put("berry_cream_sweet_roll", new String[]{null, "tooltip.createfood.berry_cream_frosting_ingredient"});
        TIPS.put("berry_cream_sweet_roll_sweet_berry", new String[]{null, "tooltip.createfood.berry_cream_frosting_ingredient", "tooltip.createfood.berry_ingredient"});
        TIPS.put("berry_cream_white_chocolate", new String[]{null, "tooltip.createfood.berry_cream_frosting_ingredient"});
        TIPS.put("berry_ice_cream_sandwich", new String[]{null, "tooltip.createfood.berry_ice_cream_ingredient"});
        TIPS.put("berry_jam_chocolate_donut", new String[]{null, "tooltip.createfood.berry_jam_ingredient"});
        TIPS.put("berry_jam_donut", new String[]{null, "tooltip.createfood.berry_jam_ingredient"});
        TIPS.put("berry_jam_sandwich", new String[]{null, "tooltip.createfood.berry_jam_ingredient"});
        TIPS.put("berry_muffin", new String[]{null, "tooltip.createfood.berry_ingredient"});
        TIPS.put("boiled_egg_peeled_salt", new String[]{null, "tooltip.createfood.salt_ingredient"});
        TIPS.put("bread_carrot", new String[]{null, "tooltip.createfood.carrot_ingredient"});
        TIPS.put("bread_fried_egg", new String[]{null, "tooltip.createfood.fried_egg_ingredient"});
        TIPS.put("bread_lettuce", new String[]{null, "tooltip.createfood.lettuce_ingredient"});
        TIPS.put("bread_lettuce_carrot", new String[]{null, "tooltip.createfood.lettuce_ingredient", "tooltip.createfood.carrot_ingredient"});
        TIPS.put("bread_slice_apple_jam", new String[]{null, "tooltip.createfood.apple_jam_ingredient"});
        TIPS.put("bread_slice_bacon", new String[]{null, "tooltip.createfood.bacon_ingredient"});
        TIPS.put("bread_slice_bacon_lettuce", new String[]{null, "tooltip.createfood.bacon_ingredient", "tooltip.createfood.lettuce_ingredient"});
        TIPS.put("bread_slice_bacon_lettuce_tomato", new String[]{null, "tooltip.createfood.bacon_ingredient", "tooltip.createfood.lettuce_ingredient", "tooltip.createfood.tomato_ingredient"});
        TIPS.put("bread_slice_beetroot", new String[]{null, "tooltip.createfood.beetroot_ingredient"});
        TIPS.put("bread_slice_beetroot_lettuce", new String[]{null, "tooltip.createfood.beetroot_ingredient", "tooltip.createfood.lettuce_ingredient"});
        TIPS.put("bread_slice_berry_jam", new String[]{null, "tooltip.createfood.berry_jam_ingredient"});
        TIPS.put("bread_slice_cheese", new String[]{null, "tooltip.createfood.cheese_ingredient"});
        TIPS.put("bread_slice_chorus_fruit_jam", new String[]{null, "tooltip.createfood.chorus_fruit_jam_ingredient"});
        TIPS.put("bread_slice_glow_berry_jam", new String[]{null, "tooltip.createfood.glow_berry_jam_ingredient"});
        TIPS.put("bread_slice_honey", new String[]{null, "tooltip.createfood.honey_ingredient"});
        TIPS.put("bread_slice_lettuce", new String[]{null, "tooltip.createfood.lettuce_ingredient"});
        TIPS.put("bread_slice_lettuce_tomato", new String[]{null, "tooltip.createfood.lettuce_ingredient", "tooltip.createfood.tomato_ingredient"});
        TIPS.put("bread_slice_melon_jam", new String[]{null, "tooltip.createfood.melon_jam_ingredient"});
        TIPS.put("bread_slice_mutton", new String[]{null, "tooltip.createfood.mutton_ingredient"});
        TIPS.put("bread_slice_mutton_beetroot", new String[]{null, "tooltip.createfood.mutton_ingredient", "tooltip.createfood.beetroot_ingredient"});
        TIPS.put("bread_slice_peanut_butter", new String[]{"peanut_butter", "tooltip.createfood.peanut_butter_ingredient"});
        TIPS.put("bread_slice_scrambled_egg", new String[]{null, "tooltip.createfood.scrambled_egg_ingredient"});
        TIPS.put("bread_slice_tomato", new String[]{null, "tooltip.createfood.tomato_ingredient"});
        TIPS.put("breakfast_plate", new String[]{null, "tooltip.createfood.fried_egg_ingredient", "tooltip.createfood.hash_browns_ingredient", "tooltip.createfood.toast_ingredient"});
        TIPS.put("buttered_toast", new String[]{null, "tooltip.createfood.butter_ingredient"});
        TIPS.put("butterscotch_apple", new String[]{null, "tooltip.createfood.butterscotch_ingredient"});
        TIPS.put("butterscotch_apple_slice", new String[]{null, "tooltip.createfood.butterscotch_ingredient"});
        TIPS.put("butterscotch_berries", new String[]{null, "tooltip.createfood.butterscotch_ingredient"});
        TIPS.put("butterscotch_chip_chocolate_cookie", new String[]{null, "tooltip.createfood.butterscotch_chips_ingredient"});
        TIPS.put("butterscotch_chip_chocolate_milkshake_bottle", new String[]{null, "tooltip.createfood.butterscotch_chips_ingredient"});
        TIPS.put("butterscotch_chip_cookie", new String[]{null, "tooltip.createfood.butterscotch_chips_ingredient"});
        TIPS.put("butterscotch_chip_ice_cream_cone", new String[]{null, "tooltip.createfood.butterscotch_chips_ingredient"});
        TIPS.put("butterscotch_chip_milkshake_bottle", new String[]{null, "tooltip.createfood.butterscotch_chips_ingredient"});
        TIPS.put("butterscotch_chip_mini_waffle", new String[]{null, "tooltip.createfood.butterscotch_chips_ingredient"});
        TIPS.put("butterscotch_chip_muffin", new String[]{null, "tooltip.createfood.butterscotch_chips_ingredient"});
        TIPS.put("butterscotch_chocolate", new String[]{null, "tooltip.createfood.butterscotch_ingredient"});
        TIPS.put("butterscotch_chocolate_pastry", new String[]{null, "tooltip.createfood.butterscotch_ingredient"});
        TIPS.put("butterscotch_chocolate_sweet_roll", new String[]{null, "tooltip.createfood.butterscotch_ingredient"});
        TIPS.put("butterscotch_dark_chocolate", new String[]{null, "tooltip.createfood.butterscotch_ingredient"});
        TIPS.put("butterscotch_fudge_ice_cream_bowl", new String[]{null, "tooltip.createfood.butterscotch_fudge_ingredient"});
        TIPS.put("butterscotch_marshmallow_stick", new String[]{null, "tooltip.createfood.butterscotch_ingredient"});
        TIPS.put("butterscotch_pastry", new String[]{null, "tooltip.createfood.butterscotch_ingredient"});
        TIPS.put("butterscotch_pretzel_stick", new String[]{null, "tooltip.createfood.butterscotch_ingredient"});
        TIPS.put("butterscotch_sweet_roll", new String[]{null, "tooltip.createfood.butterscotch_ingredient"});
        TIPS.put("butterscotch_toast", new String[]{null, "tooltip.createfood.butterscotch_ingredient"});
        TIPS.put("butterscotch_white_chocolate", new String[]{null, "tooltip.createfood.butterscotch_ingredient"});
        TIPS.put("caramel_apple", new String[]{null, "tooltip.createfood.caramel_ingredient"});
        TIPS.put("caramel_berries", new String[]{null, "tooltip.createfood.caramel_ingredient"});
        TIPS.put("caramel_chip_chocolate_cookie", new String[]{null, "tooltip.createfood.caramel_chips_ingredient"});
        TIPS.put("caramel_chip_chocolate_milkshake_bottle", new String[]{null, "tooltip.createfood.caramel_chips_ingredient"});
        TIPS.put("caramel_chip_cookie", new String[]{null, "tooltip.createfood.caramel_chips_ingredient"});
        TIPS.put("caramel_chip_ice_cream_cone", new String[]{null, "tooltip.createfood.caramel_chips_ingredient"});
        TIPS.put("caramel_chip_milkshake_bottle", new String[]{null, "tooltip.createfood.caramel_chips_ingredient"});
        TIPS.put("caramel_chip_mini_waffle", new String[]{null, "tooltip.createfood.caramel_chips_ingredient"});
        TIPS.put("caramel_chip_muffin", new String[]{null, "tooltip.createfood.caramel_chips_ingredient"});
        TIPS.put("caramel_chocolate", new String[]{null, "tooltip.createfood.caramel_ingredient"});
        TIPS.put("caramel_chocolate_pastry", new String[]{null, "tooltip.createfood.caramel_ingredient"});
        TIPS.put("caramel_chocolate_sweet_roll", new String[]{null, "tooltip.createfood.caramel_ingredient"});
        TIPS.put("caramel_dark_chocolate", new String[]{null, "tooltip.createfood.caramel_ingredient"});
        TIPS.put("caramel_fudge_ice_cream_bowl", new String[]{null, "tooltip.createfood.caramel_fudge_ingredient"});
        TIPS.put("caramel_marshmallow_stick", new String[]{null, "tooltip.createfood.caramel_ingredient"});
        TIPS.put("caramel_pastry", new String[]{null, "tooltip.createfood.caramel_ingredient"});
        TIPS.put("caramel_popcorn", new String[]{"corn", "tooltip.createfood.caramel_ingredient"});
        TIPS.put("caramel_pretzel_stick", new String[]{null, "tooltip.createfood.caramel_ingredient"});
        TIPS.put("caramel_sweet_roll", new String[]{null, "tooltip.createfood.caramel_ingredient"});
        TIPS.put("caramel_toast", new String[]{null, "tooltip.createfood.caramel_ingredient"});
        TIPS.put("caramel_white_chocolate", new String[]{null, "tooltip.createfood.caramel_ingredient"});
        TIPS.put("cheeseburger_bacon", new String[]{null, "tooltip.createfood.bacon_ingredient"});
        TIPS.put("cheeseburger_bacon_lettuce", new String[]{null, "tooltip.createfood.bacon_ingredient", "tooltip.createfood.lettuce_ingredient"});
        TIPS.put("cheeseburger_bacon_lettuce_tomato", new String[]{null, "tooltip.createfood.bacon_ingredient", "tooltip.createfood.lettuce_ingredient", "tooltip.createfood.tomato_ingredient"});
        TIPS.put("cheeseburger_lettuce", new String[]{null, "tooltip.createfood.lettuce_ingredient"});
        TIPS.put("cheeseburger_lettuce_tomato", new String[]{null, "tooltip.createfood.lettuce_ingredient", "tooltip.createfood.tomato_ingredient"});
        TIPS.put("cheeseburger_onion", new String[]{null, "tooltip.createfood.onion_ingredient"});
        TIPS.put("cheeseburger_onion_bacon", new String[]{null, "tooltip.createfood.onion_ingredient", "tooltip.createfood.bacon_ingredient"});
        TIPS.put("cheeseburger_onion_bacon_lettuce", new String[]{null, "tooltip.createfood.onion_ingredient", "tooltip.createfood.bacon_ingredient", "tooltip.createfood.lettuce_ingredient"});
        TIPS.put("cheeseburger_onion_lettuce", new String[]{null, "tooltip.createfood.onion_ingredient", "tooltip.createfood.lettuce_ingredient"});
        TIPS.put("cheeseburger_onion_lettuce_tomato", new String[]{null, "tooltip.createfood.onion_ingredient", "tooltip.createfood.lettuce_ingredient", "tooltip.createfood.tomato_ingredient"});
        TIPS.put("cheeseburger_tomato", new String[]{null, "tooltip.createfood.tomato_ingredient"});
        TIPS.put("cheese_biscuit", new String[]{null, "tooltip.createfood.cheese_ingredient"});
        TIPS.put("cheese_biscuit_sandwich", new String[]{null, "tooltip.createfood.cheese_ingredient"});
        TIPS.put("cheese_calzone", new String[]{null, "tooltip.createfood.cheese_ingredient"});
        TIPS.put("cheese_pizza_slice", new String[]{null, "tooltip.createfood.cheese_ingredient"});
        TIPS.put("cheese_potato_dumplings", new String[]{null, "tooltip.createfood.potato_ingredient", "tooltip.createfood.cheese_ingredient", "tooltip.createfood.onion_ingredient"});
        TIPS.put("cheese_pretzel_stick", new String[]{null, "tooltip.createfood.cheese_ingredient"});
        TIPS.put("cheese_sandwich", new String[]{null, "tooltip.createfood.cheese_ingredient"});
        TIPS.put("chicken_bun_bacon", new String[]{null, "tooltip.createfood.bacon_ingredient"});
        TIPS.put("chicken_bun_bacon_lettuce", new String[]{null, "tooltip.createfood.bacon_ingredient", "tooltip.createfood.lettuce_ingredient"});
        TIPS.put("chicken_bun_cheese", new String[]{null, "tooltip.createfood.cheese_ingredient"});
        TIPS.put("chicken_bun_cheese_bacon", new String[]{null, "tooltip.createfood.cheese_ingredient", "tooltip.createfood.bacon_ingredient"});
        TIPS.put("chicken_bun_cheese_bacon_lettuce", new String[]{null, "tooltip.createfood.cheese_ingredient", "tooltip.createfood.bacon_ingredient", "tooltip.createfood.lettuce_ingredient"});
        TIPS.put("chicken_bun_cheese_lettuce", new String[]{null, "tooltip.createfood.cheese_ingredient", "tooltip.createfood.lettuce_ingredient"});
        TIPS.put("chicken_bun_cheese_lettuce_tomato", new String[]{null, "tooltip.createfood.cheese_ingredient", "tooltip.createfood.lettuce_ingredient", "tooltip.createfood.tomato_ingredient"});
        TIPS.put("chicken_bun_cheese_tomato", new String[]{null, "tooltip.createfood.cheese_ingredient", "tooltip.createfood.tomato_ingredient"});
        TIPS.put("chicken_bun_lettuce", new String[]{null, "tooltip.createfood.lettuce_ingredient"});
        TIPS.put("chicken_bun_lettuce_tomato", new String[]{null, "tooltip.createfood.lettuce_ingredient", "tooltip.createfood.tomato_ingredient"});
        TIPS.put("chicken_bun_tomato", new String[]{null, "tooltip.createfood.tomato_ingredient"});
        TIPS.put("chicken_burger_bacon", new String[]{null, "tooltip.createfood.bacon_ingredient"});
        TIPS.put("chicken_burger_bacon_lettuce", new String[]{null, "tooltip.createfood.bacon_ingredient", "tooltip.createfood.lettuce_ingredient"});
        TIPS.put("chicken_burger_lettuce", new String[]{null, "tooltip.createfood.lettuce_ingredient"});
        TIPS.put("chicken_burger_lettuce_tomato", new String[]{null, "tooltip.createfood.lettuce_ingredient", "tooltip.createfood.tomato_ingredient"});
        TIPS.put("chicken_burger_tomato", new String[]{null, "tooltip.createfood.tomato_ingredient"});
        TIPS.put("chicken_burrito_rice", new String[]{null, "tooltip.createfood.chicken_ingredient", "tooltip.createfood.rice_ingredient"});
        TIPS.put("chicken_calzone", new String[]{null, "tooltip.createfood.cheese_ingredient", "tooltip.createfood.chicken_ingredient"});
        TIPS.put("chicken_cheeseburger_bacon", new String[]{null, "tooltip.createfood.bacon_ingredient"});
        TIPS.put("chicken_cheeseburger_bacon_lettuce", new String[]{null, "tooltip.createfood.bacon_ingredient", "tooltip.createfood.lettuce_ingredient"});
        TIPS.put("chicken_cheeseburger_lettuce", new String[]{null, "tooltip.createfood.lettuce_ingredient"});
        TIPS.put("chicken_cheeseburger_lettuce_tomato", new String[]{null, "tooltip.createfood.lettuce_ingredient", "tooltip.createfood.tomato_ingredient"});
        TIPS.put("chicken_cheeseburger_tomato", new String[]{null, "tooltip.createfood.tomato_ingredient"});
        TIPS.put("chicken_rice_bowl", new String[]{null, "tooltip.createfood.kelp_ingredient"});
        TIPS.put("chicken_taco", new String[]{null, "tooltip.createfood.chicken_ingredient"});
        TIPS.put("chicken_taco_lettuce", new String[]{null, "tooltip.createfood.chicken_ingredient", "tooltip.createfood.lettuce_ingredient"});
        TIPS.put("chicken_taco_lettuce_taco_sauce", new String[]{null, "tooltip.createfood.chicken_ingredient", "tooltip.createfood.lettuce_ingredient", "tooltip.createfood.taco_sauce_ingredient"});
        TIPS.put("chicken_wrap_onion_tomato", new String[]{null, "tooltip.createfood.chicken_ingredient", "tooltip.createfood.onion_ingredient", "tooltip.createfood.tomato_ingredient"});
        TIPS.put("chocolate_apple", new String[]{null, "tooltip.createfood.chocolate_ingredient"});
        TIPS.put("chocolate_apple_slice", new String[]{null, "tooltip.createfood.chocolate_ingredient"});
        TIPS.put("chocolate_chip_chocolate_cookie", new String[]{null, "tooltip.createfood.chocolate_chips_ingredient"});
        TIPS.put("chocolate_chip_chocolate_milkshake_bottle", new String[]{null, "tooltip.createfood.chocolate_chips_ingredient"});
        TIPS.put("chocolate_chip_ice_cream_cone", new String[]{null, "tooltip.createfood.chocolate_chips_ingredient"});
        TIPS.put("chocolate_chip_milkshake_bottle", new String[]{null, "tooltip.createfood.chocolate_chips_ingredient"});
        TIPS.put("chocolate_chip_mini_waffle", new String[]{null, "tooltip.createfood.chocolate_chips_ingredient"});
        TIPS.put("chocolate_chip_muffin", new String[]{null, "tooltip.createfood.chocolate_chips_ingredient"});
        TIPS.put("chocolate_chocolate_pastry", new String[]{null, "tooltip.createfood.chocolate_ingredient"});
        TIPS.put("chocolate_cream_cake_slice", new String[]{null, "tooltip.createfood.chocolate_cream_frosting_ingredient"});
        TIPS.put("chocolate_cream_cake_slice_butterscotch", new String[]{null, "tooltip.createfood.chocolate_cream_frosting_ingredient", "tooltip.createfood.butterscotch_chips_ingredient"});
        TIPS.put("chocolate_cream_cake_slice_caramel", new String[]{null, "tooltip.createfood.chocolate_cream_frosting_ingredient", "tooltip.createfood.caramel_ingredient"});
        TIPS.put("chocolate_cream_cake_slice_chocolate", new String[]{null, "tooltip.createfood.chocolate_cream_frosting_ingredient", "tooltip.createfood.chocolate_chips_ingredient"});
        TIPS.put("chocolate_cream_cake_slice_dark_chocolate", new String[]{null, "tooltip.createfood.chocolate_cream_frosting_ingredient", "tooltip.createfood.dark_chocolate_chips_ingredient"});
        TIPS.put("chocolate_cream_cake_slice_toffee", new String[]{null, "tooltip.createfood.chocolate_cream_frosting_ingredient", "tooltip.createfood.toffee_chips_ingredient"});
        TIPS.put("chocolate_cream_cake_slice_white_chocolate", new String[]{null, "tooltip.createfood.chocolate_cream_frosting_ingredient", "tooltip.createfood.white_chocolate_chips_ingredient"});
        TIPS.put("chocolate_cream_chocolate_cake_slice", new String[]{null, "tooltip.createfood.chocolate_cream_frosting_ingredient"});
        TIPS.put("chocolate_cream_chocolate_cupcake", new String[]{null, "tooltip.createfood.chocolate_cream_frosting_ingredient"});
        TIPS.put("chocolate_cream_chocolate_donut", new String[]{null, "tooltip.createfood.chocolate_cream_frosting_ingredient"});
        TIPS.put("chocolate_cream_chocolate_sweet_roll", new String[]{null, "tooltip.createfood.chocolate_cream_frosting_ingredient"});
        TIPS.put("chocolate_cream_cupcake", new String[]{null, "tooltip.createfood.chocolate_cream_frosting_ingredient"});
        TIPS.put("chocolate_cream_donut", new String[]{null, "tooltip.createfood.chocolate_cream_frosting_ingredient"});
        TIPS.put("chocolate_cream_frosting_piping_bag", new String[]{null, "tooltip.createfood.chocolate_cream_frosting_ingredient"});
        TIPS.put("chocolate_cream_mini_waffle", new String[]{null, "tooltip.createfood.chocolate_cream_frosting_ingredient"});
        TIPS.put("chocolate_cream_sweet_roll", new String[]{null, "tooltip.createfood.chocolate_cream_frosting_ingredient"});
        TIPS.put("chocolate_donut_hole_sugar", new String[]{null, "tooltip.createfood.sugar_ingredient"});
        TIPS.put("chocolate_donut_sugar", new String[]{null, "tooltip.createfood.sugar_ingredient"});
        TIPS.put("chocolate_fudge_ice_cream_bowl", new String[]{null, "tooltip.createfood.chocolate_fudge_ingredient"});
        TIPS.put("chocolate_graham_cracker_apple_ice_cream", new String[]{null, "tooltip.createfood.apple_ice_cream_ingredient"});
        TIPS.put("chocolate_graham_cracker_berry_ice_cream", new String[]{null, "tooltip.createfood.berry_ice_cream_ingredient"});
        TIPS.put("chocolate_graham_cracker_chocolate_ice_cream", new String[]{null, "tooltip.createfood.chocolate_ice_cream_ingredient"});
        TIPS.put("chocolate_graham_cracker_chorus_fruit_ice_cream", new String[]{null, "tooltip.createfood.chorus_fruit_ice_cream_ingredient"});
        TIPS.put("chocolate_graham_cracker_glow_berry_ice_cream", new String[]{null, "tooltip.createfood.berry_ice_cream_ingredient"});
        TIPS.put("chocolate_graham_cracker_ice_cream", new String[]{null, "tooltip.createfood.ice_cream_ingredient"});
        TIPS.put("chocolate_graham_cracker_melon_ice_cream", new String[]{null, "tooltip.createfood.melon_ice_cream_ingredient"});
        TIPS.put("chocolate_ice_cream_sandwich", new String[]{null, "tooltip.createfood.chocolate_ice_cream_ingredient"});
        TIPS.put("chocolate_marshmallow_stick", new String[]{null, "tooltip.createfood.chocolate_ingredient"});
        TIPS.put("chocolate_pastry", new String[]{null, "tooltip.createfood.chocolate_ingredient"});
        TIPS.put("chocolate_pie_graham_cracker_slice", new String[]{null, "tooltip.createfood.graham_cracker_pie_crust_ingredient"});
        TIPS.put("chocolate_pretzel_stick", new String[]{null, "tooltip.createfood.chocolate_ingredient"});
        TIPS.put("chocolate_toast", new String[]{null, "tooltip.createfood.chocolate_ingredient"});
        TIPS.put("chorus_fruit_cookie", new String[]{null, "tooltip.createfood.chorus_fruit_ingredient"});
        TIPS.put("chorus_fruit_cream_cake_slice", new String[]{null, "tooltip.createfood.chorus_fruit_cream_frosting_ingredient"});
        TIPS.put("chorus_fruit_cream_cake_slice_chorus_fruit", new String[]{null, "tooltip.createfood.chorus_fruit_cream_frosting_ingredient", "tooltip.createfood.chorus_fruit_ingredient"});
        TIPS.put("chorus_fruit_cream_cake_slice_glow_berry", new String[]{null, "tooltip.createfood.chorus_fruit_cream_frosting_ingredient", "tooltip.createfood.glow_berry_ingredient"});
        TIPS.put("chorus_fruit_cream_cake_slice_sweet_berry", new String[]{null, "tooltip.createfood.chorus_fruit_cream_frosting_ingredient", "tooltip.createfood.berry_ingredient"});
        TIPS.put("chorus_fruit_cream_chocolate", new String[]{null, "tooltip.createfood.chorus_fruit_cream_frosting_ingredient"});
        TIPS.put("chorus_fruit_cream_chocolate_cupcake", new String[]{null, "tooltip.createfood.chorus_fruit_cream_frosting_ingredient"});
        TIPS.put("chorus_fruit_cream_chocolate_donut", new String[]{null, "tooltip.createfood.chorus_fruit_cream_frosting_ingredient"});
        TIPS.put("chorus_fruit_cream_chocolate_pastry", new String[]{null, "tooltip.createfood.chorus_fruit_cream_frosting_ingredient"});
        TIPS.put("chorus_fruit_cream_chocolate_sweet_roll", new String[]{null, "tooltip.createfood.chorus_fruit_cream_frosting_ingredient"});
        TIPS.put("chorus_fruit_cream_chocolate_sweet_roll_chorus_fruit", new String[]{null, "tooltip.createfood.chorus_fruit_cream_frosting_ingredient", "tooltip.createfood.chorus_fruit_ingredient"});
        TIPS.put("chorus_fruit_cream_cupcake", new String[]{null, "tooltip.createfood.chorus_fruit_cream_frosting_ingredient"});
        TIPS.put("chorus_fruit_cream_dark_chocolate", new String[]{null, "tooltip.createfood.chorus_fruit_cream_frosting_ingredient"});
        TIPS.put("chorus_fruit_cream_donut", new String[]{null, "tooltip.createfood.chorus_fruit_cream_frosting_ingredient"});
        TIPS.put("chorus_fruit_cream_frosting_piping_bag", new String[]{null, "tooltip.createfood.chorus_fruit_cream_frosting_ingredient"});
        TIPS.put("chorus_fruit_cream_mini_waffle", new String[]{null, "tooltip.createfood.chorus_fruit_cream_frosting_ingredient"});
        TIPS.put("chorus_fruit_cream_mini_waffle_chorus_fruit", new String[]{null, "tooltip.createfood.chorus_fruit_cream_frosting_ingredient", "tooltip.createfood.chorus_fruit_ingredient"});
        TIPS.put("chorus_fruit_cream_pastry", new String[]{null, "tooltip.createfood.chorus_fruit_cream_frosting_ingredient"});
        TIPS.put("chorus_fruit_cream_sweet_roll", new String[]{null, "tooltip.createfood.chorus_fruit_cream_frosting_ingredient"});
        TIPS.put("chorus_fruit_cream_sweet_roll_chorus_fruit", new String[]{null, "tooltip.createfood.chorus_fruit_cream_frosting_ingredient", "tooltip.createfood.chorus_fruit_ingredient"});
        TIPS.put("chorus_fruit_cream_white_chocolate", new String[]{null, "tooltip.createfood.chorus_fruit_cream_frosting_ingredient"});
        TIPS.put("chorus_fruit_ice_cream_sandwich", new String[]{null, "tooltip.createfood.chorus_fruit_ice_cream_ingredient"});
        TIPS.put("chorus_fruit_jam_chocolate_donut", new String[]{null, "tooltip.createfood.chorus_fruit_jam_ingredient"});
        TIPS.put("chorus_fruit_jam_donut", new String[]{null, "tooltip.createfood.chorus_fruit_jam_ingredient"});
        TIPS.put("chorus_fruit_jam_sandwich", new String[]{null, "tooltip.createfood.chorus_fruit_jam_ingredient"});
        TIPS.put("chorus_fruit_muffin", new String[]{null, "tooltip.createfood.chorus_fruit_ingredient"});
        TIPS.put("cinnamon_sweet_roll_base", new String[]{"cinnamon"});
        TIPS.put("coffee_toffee", new String[]{"coffee"});
        TIPS.put("coffee_toffee_fudge", new String[]{"coffee"});
        TIPS.put("corn_flour", new String[]{"corn"});
        TIPS.put("corn_stick", new String[]{"corn"});
        TIPS.put("cream_cake_slice", new String[]{null, "tooltip.createfood.cream_frosting_ingredient"});
        TIPS.put("cream_cake_slice_chorus_fruit", new String[]{null, "tooltip.createfood.cream_frosting_ingredient", "tooltip.createfood.chorus_fruit_ingredient"});
        TIPS.put("cream_cake_slice_glow_berry", new String[]{null, "tooltip.createfood.cream_frosting_ingredient", "tooltip.createfood.glow_berry_ingredient"});
        TIPS.put("cream_chocolate", new String[]{null, "tooltip.createfood.cream_frosting_ingredient"});
        TIPS.put("cream_chocolate_cake_slice", new String[]{null, "tooltip.createfood.cream_frosting_ingredient"});
        TIPS.put("cream_chocolate_cupcake", new String[]{null, "tooltip.createfood.cream_frosting_ingredient"});
        TIPS.put("cream_chocolate_donut", new String[]{null, "tooltip.createfood.cream_frosting_ingredient"});
        TIPS.put("cream_chocolate_pastry", new String[]{null, "tooltip.createfood.cream_frosting_ingredient"});
        TIPS.put("cream_chocolate_sweet_roll", new String[]{null, "tooltip.createfood.cream_frosting_ingredient"});
        TIPS.put("cream_chocolate_sweet_roll_chorus_fruit", new String[]{null, "tooltip.createfood.cream_frosting_ingredient", "tooltip.createfood.chorus_fruit_ingredient"});
        TIPS.put("cream_chocolate_sweet_roll_glow_berry", new String[]{null, "tooltip.createfood.cream_frosting_ingredient", "tooltip.createfood.glow_berry_ingredient"});
        TIPS.put("cream_chocolate_sweet_roll_sweet_berry", new String[]{null, "tooltip.createfood.cream_frosting_ingredient", "tooltip.createfood.berry_ingredient"});
        TIPS.put("cream_cupcake", new String[]{null, "tooltip.createfood.cream_frosting_ingredient"});
        TIPS.put("cream_dark_chocolate", new String[]{null, "tooltip.createfood.cream_frosting_ingredient"});
        TIPS.put("cream_donut", new String[]{null, "tooltip.createfood.cream_frosting_ingredient"});
        TIPS.put("cream_frosting_piping_bag", new String[]{null, "tooltip.createfood.cream_frosting_ingredient"});
        TIPS.put("cream_mini_waffle", new String[]{null, "tooltip.createfood.cream_frosting_ingredient"});
        TIPS.put("cream_mini_waffle_chorus_fruit", new String[]{null, "tooltip.createfood.cream_frosting_ingredient", "tooltip.createfood.chorus_fruit_ingredient"});
        TIPS.put("cream_mini_waffle_glow_berry", new String[]{null, "tooltip.createfood.cream_frosting_ingredient", "tooltip.createfood.glow_berry_ingredient"});
        TIPS.put("cream_mini_waffle_sweet_berry", new String[]{null, "tooltip.createfood.cream_frosting_ingredient", "tooltip.createfood.berry_ingredient"});
        TIPS.put("cream_pastry", new String[]{null, "tooltip.createfood.cream_frosting_ingredient"});
        TIPS.put("cream_pie_chocolate_graham_cracker_slice", new String[]{null, "tooltip.createfood.chocolate_graham_cracker_pie_crust_ingredient"});
        TIPS.put("cream_pie_graham_cracker_slice", new String[]{null, "tooltip.createfood.graham_cracker_pie_crust_ingredient"});
        TIPS.put("cream_sweet_roll_chorus_fruit", new String[]{null, "tooltip.createfood.cream_frosting_ingredient", "tooltip.createfood.chorus_fruit_ingredient"});
        TIPS.put("cream_sweet_roll_glow_berry", new String[]{null, "tooltip.createfood.cream_frosting_ingredient", "tooltip.createfood.glow_berry_ingredient"});
        TIPS.put("cream_sweet_roll_sweet_berry", new String[]{null, "tooltip.createfood.cream_frosting_ingredient", "tooltip.createfood.berry_ingredient"});
        TIPS.put("cream_white_chocolate", new String[]{null, "tooltip.createfood.cream_frosting_ingredient"});
        TIPS.put("custard_sugar_bottle", new String[]{null, "tooltip.createfood.sugar_ingredient"});
        TIPS.put("dark_chocolate_apple", new String[]{null, "tooltip.createfood.dark_chocolate_ingredient"});
        TIPS.put("dark_chocolate_apple_slice", new String[]{null, "tooltip.createfood.dark_chocolate_ingredient"});
        TIPS.put("dark_chocolate_berries", new String[]{null, "tooltip.createfood.dark_chocolate_ingredient"});
        TIPS.put("dark_chocolate_chip_chocolate_cookie", new String[]{null, "tooltip.createfood.dark_chocolate_chips_ingredient"});
        TIPS.put("dark_chocolate_chip_chocolate_milkshake_bottle", new String[]{null, "tooltip.createfood.dark_chocolate_chips_ingredient"});
        TIPS.put("dark_chocolate_chip_cookie", new String[]{null, "tooltip.createfood.dark_chocolate_chips_ingredient"});
        TIPS.put("dark_chocolate_chip_ice_cream_cone", new String[]{null, "tooltip.createfood.dark_chocolate_chips_ingredient"});
        TIPS.put("dark_chocolate_chip_milkshake_bottle", new String[]{null, "tooltip.createfood.dark_chocolate_chips_ingredient"});
        TIPS.put("dark_chocolate_chip_mini_waffle", new String[]{null, "tooltip.createfood.dark_chocolate_chips_ingredient"});
        TIPS.put("dark_chocolate_chip_muffin", new String[]{null, "tooltip.createfood.dark_chocolate_chips_ingredient"});
        TIPS.put("dark_chocolate_chocolate_pastry", new String[]{null, "tooltip.createfood.dark_chocolate_ingredient"});
        TIPS.put("dark_chocolate_marshmallow_stick", new String[]{null, "tooltip.createfood.dark_chocolate_ingredient"});
        TIPS.put("dark_chocolate_pastry", new String[]{null, "tooltip.createfood.dark_chocolate_ingredient"});
        TIPS.put("dark_chocolate_pretzel_stick", new String[]{null, "tooltip.createfood.dark_chocolate_ingredient"});
        TIPS.put("dark_chocolate_toast", new String[]{null, "tooltip.createfood.dark_chocolate_ingredient"});
        TIPS.put("donut_hole_sugar", new String[]{null, "tooltip.createfood.sugar_ingredient"});
        TIPS.put("donut_sugar", new String[]{null, "tooltip.createfood.sugar_ingredient"});
        TIPS.put("dragon_bun", new String[]{"dragon_meat"});
        TIPS.put("dragon_bun_crimson_fungus", new String[]{"dragon_meat", "tooltip.createfood.crimson_fungus_ingredient"});
        TIPS.put("dragon_bun_warped_fungus", new String[]{"dragon_meat", "tooltip.createfood.warped_fungus_ingredient"});
        TIPS.put("dragon_burger", new String[]{"dragon_meat"});
        TIPS.put("dragon_burger_crimson_fungus", new String[]{"dragon_meat", "tooltip.createfood.crimson_fungus_ingredient"});
        TIPS.put("dragon_burger_warped_fungus", new String[]{"dragon_meat", "tooltip.createfood.warped_fungus_ingredient"});
        TIPS.put("dragon_patty", new String[]{"dragon_meat"});
        TIPS.put("dried_coffee_beans", new String[]{"coffee"});
        TIPS.put("eggplant_bun", new String[]{"eggplant"});
        TIPS.put("eggplant_bun_cheese", new String[]{"eggplant", "tooltip.createfood.cheese_ingredient"});
        TIPS.put("eggplant_bun_cheese_lettuce", new String[]{"eggplant", "tooltip.createfood.cheese_ingredient", "tooltip.createfood.lettuce_ingredient"});
        TIPS.put("eggplant_bun_cheese_lettuce_tomato", new String[]{"eggplant", "tooltip.createfood.cheese_ingredient", "tooltip.createfood.lettuce_ingredient", "tooltip.createfood.tomato_ingredient"});
        TIPS.put("eggplant_bun_cheese_tomato", new String[]{"eggplant", "tooltip.createfood.cheese_ingredient", "tooltip.createfood.tomato_ingredient"});
        TIPS.put("eggplant_bun_lettuce", new String[]{"eggplant", "tooltip.createfood.lettuce_ingredient", "tooltip.createfood.tomato_ingredient"});
        TIPS.put("eggplant_bun_lettuce_tomato", new String[]{"eggplant", "tooltip.createfood.lettuce_ingredient"});
        TIPS.put("eggplant_bun_tomato", new String[]{"eggplant", "tooltip.createfood.tomato_ingredient"});
        TIPS.put("eggplant_burger", new String[]{"eggplant"});
        TIPS.put("eggplant_burger_lettuce", new String[]{"eggplant", "tooltip.createfood.lettuce_ingredient"});
        TIPS.put("eggplant_burger_tomato", new String[]{"eggplant", "tooltip.createfood.tomato_ingredient"});
        TIPS.put("eggplant_cheeseburger", new String[]{"eggplant"});
        TIPS.put("eggplant_cheeseburger_lettuce", new String[]{"eggplant", "tooltip.createfood.lettuce_ingredient"});
        TIPS.put("eggplant_cheeseburger_lettuce_tomato", new String[]{"eggplant", "tooltip.createfood.lettuce_ingredient", "tooltip.createfood.tomato_ingredient"});
        TIPS.put("eggplant_cheeseburger_tomato", new String[]{"eggplant", "tooltip.createfood.tomato_ingredient"});
        TIPS.put("egg_burrito", new String[]{null, "tooltip.createfood.egg_ingredient"});
        TIPS.put("egg_burrito_bacon", new String[]{null, "tooltip.createfood.egg_ingredient", "tooltip.createfood.bacon_ingredient"});
        TIPS.put("egg_burrito_cheese", new String[]{null, "tooltip.createfood.egg_ingredient", "tooltip.createfood.cheese_ingredient"});
        TIPS.put("egg_burrito_cheese_bacon", new String[]{null, "tooltip.createfood.egg_ingredient", "tooltip.createfood.cheese_ingredient", "tooltip.createfood.bacon_ingredient"});
        TIPS.put("egg_burrito_cheese_sausage", new String[]{null, "tooltip.createfood.egg_ingredient", "tooltip.createfood.cheese_ingredient", "tooltip.createfood.sausage_ingredient"});
        TIPS.put("egg_burrito_cheese_sausage_bacon", new String[]{null, "tooltip.createfood.egg_ingredient", "tooltip.createfood.cheese_ingredient", "tooltip.createfood.sausage_ingredient", "tooltip.createfood.bacon_ingredient"});
        TIPS.put("egg_burrito_sausage", new String[]{null, "tooltip.createfood.egg_ingredient", "tooltip.createfood.sausage_ingredient"});
        TIPS.put("egg_dumplings", new String[]{null, "tooltip.createfood.egg_ingredient", "tooltip.createfood.onion_ingredient"});
        TIPS.put("endermite_meatball", new String[]{"endermite_meat"});
        TIPS.put("endermite_meatball_sandwich", new String[]{"endermite_meat", "tooltip.createfood.endermite_meatballs_ingredient"});
        TIPS.put("espresso_powder", new String[]{"coffee"});
        TIPS.put("fish_bacon_pizza_slice", new String[]{null, "tooltip.createfood.fish_ingredient", "tooltip.createfood.bacon_ingredient"});
        TIPS.put("fish_burrito_rice", new String[]{null, "tooltip.createfood.fish_ingredient", "tooltip.createfood.rice_ingredient"});
        TIPS.put("fish_calzone", new String[]{null, "tooltip.createfood.cheese_ingredient", "tooltip.createfood.fish_ingredient"});
        TIPS.put("fish_chowder_bowl", new String[]{null, "tooltip.createfood.fish_ingredient"});
        TIPS.put("fish_onion_pizza_slice", new String[]{null, "tooltip.createfood.fish_ingredient", "tooltip.createfood.onion_ingredient"});
        TIPS.put("fish_pizza_slice", new String[]{null, "tooltip.createfood.fish_ingredient"});
        TIPS.put("fish_rice_bowl", new String[]{null, "tooltip.createfood.kelp_ingredient"});
        TIPS.put("fish_taco", new String[]{null, "tooltip.createfood.fish_ingredient"});
        TIPS.put("fish_taco_kelp", new String[]{null, "tooltip.createfood.fish_ingredient", "tooltip.createfood.kelp_ingredient"});
        TIPS.put("fish_taco_kelp_taco_sauce", new String[]{null, "tooltip.createfood.fish_ingredient", "tooltip.createfood.kelp_ingredient", "tooltip.createfood.taco_sauce_ingredient"});
        TIPS.put("fish_wrap_kelp_onion", new String[]{null, "tooltip.createfood.fish_ingredient", "tooltip.createfood.kelp_ingredient", "tooltip.createfood.onion_ingredient"});
        TIPS.put("fried_egg_hash_brown_sandwich", new String[]{null, "tooltip.createfood.fried_egg_ingredient", "tooltip.createfood.hash_browns_ingredient"});
        TIPS.put("glow_berry_cookie", new String[]{null, "tooltip.createfood.glow_berry_ingredient"});
        TIPS.put("glow_berry_cream_cake_slice", new String[]{null, "tooltip.createfood.glow_berry_cream_frosting_ingredient"});
        TIPS.put("glow_berry_cream_cake_slice_chorus_fruit", new String[]{null, "tooltip.createfood.glow_berry_cream_frosting_ingredient", "tooltip.createfood.chorus_fruit_ingredient"});
        TIPS.put("glow_berry_cream_cake_slice_glow_berry", new String[]{null, "tooltip.createfood.glow_berry_cream_frosting_ingredient", "tooltip.createfood.glow_berry_ingredient"});
        TIPS.put("glow_berry_cream_cake_slice_sweet_berry", new String[]{null, "tooltip.createfood.glow_berry_cream_frosting_ingredient", "tooltip.createfood.berry_ingredient"});
        TIPS.put("glow_berry_cream_chocolate", new String[]{null, "tooltip.createfood.glow_berry_cream_frosting_ingredient"});
        TIPS.put("glow_berry_cream_chocolate_cupcake", new String[]{null, "tooltip.createfood.glow_berry_cream_frosting_ingredient"});
        TIPS.put("glow_berry_cream_chocolate_donut", new String[]{null, "tooltip.createfood.glow_berry_cream_frosting_ingredient"});
        TIPS.put("glow_berry_cream_chocolate_pastry", new String[]{null, "tooltip.createfood.glow_berry_cream_frosting_ingredient"});
        TIPS.put("glow_berry_cream_chocolate_sweet_roll", new String[]{null, "tooltip.createfood.glow_berry_cream_frosting_ingredient"});
        TIPS.put("glow_berry_cream_chocolate_sweet_roll_glow_berry", new String[]{null, "tooltip.createfood.glow_berry_cream_frosting_ingredient"});
        TIPS.put("glow_berry_cream_cupcake", new String[]{null, "tooltip.createfood.glow_berry_cream_frosting_ingredient"});
        TIPS.put("glow_berry_cream_dark_chocolate", new String[]{null, "tooltip.createfood.glow_berry_cream_frosting_ingredient"});
        TIPS.put("glow_berry_cream_donut", new String[]{null, "tooltip.createfood.glow_berry_cream_frosting_ingredient"});
        TIPS.put("glow_berry_cream_frosting_piping_bag", new String[]{null, "tooltip.createfood.glow_berry_cream_frosting_ingredient"});
        TIPS.put("glow_berry_cream_mini_waffle", new String[]{null, "tooltip.createfood.glow_berry_cream_frosting_ingredient"});
        TIPS.put("glow_berry_cream_mini_waffle_glow_berry", new String[]{null, "tooltip.createfood.glow_berry_cream_frosting_ingredient"});
        TIPS.put("glow_berry_cream_pastry", new String[]{null, "tooltip.createfood.glow_berry_cream_frosting_ingredient"});
        TIPS.put("glow_berry_cream_sweet_roll", new String[]{null, "tooltip.createfood.glow_berry_cream_frosting_ingredient"});
        TIPS.put("glow_berry_cream_sweet_roll_glow_berry", new String[]{null, "tooltip.createfood.glow_berry_cream_frosting_ingredient"});
        TIPS.put("glow_berry_cream_white_chocolate", new String[]{null, "tooltip.createfood.glow_berry_cream_frosting_ingredient"});
        TIPS.put("glow_berry_ice_cream_sandwich", new String[]{null, "tooltip.createfood.glow_berry_ice_cream_ingredient"});
        TIPS.put("glow_berry_jam_chocolate_donut", new String[]{null, "tooltip.createfood.glow_berry_jam_ingredient"});
        TIPS.put("glow_berry_jam_donut", new String[]{null, "tooltip.createfood.glow_berry_jam_ingredient"});
        TIPS.put("glow_berry_jam_sandwich", new String[]{null, "tooltip.createfood.glow_berry_jam_ingredient"});
        TIPS.put("glow_berry_muffin", new String[]{null, "tooltip.createfood.glow_berry_ingredient"});
        TIPS.put("graham_cracker_chocolate", new String[]{null, "tooltip.createfood.chocolate_ingredient"});
        TIPS.put("graham_cracker_chocolate_marshmallow", new String[]{null, "tooltip.createfood.chocolate_ingredient", "tooltip.createfood.marshmallow_ingredient"});
        TIPS.put("graham_cracker_marshmallow", new String[]{null, "tooltip.createfood.marshmallow_ingredient"});
        TIPS.put("ground_endermite", new String[]{"endermite_meat"});
        TIPS.put("hamburger_bacon", new String[]{null, "tooltip.createfood.bacon_ingredient"});
        TIPS.put("hamburger_bacon_lettuce", new String[]{null, "tooltip.createfood.bacon_ingredient", "tooltip.createfood.lettuce_ingredient"});
        TIPS.put("hamburger_bacon_lettuce_tomato", new String[]{null, "tooltip.createfood.bacon_ingredient", "tooltip.createfood.lettuce_ingredient", "tooltip.createfood.tomato_ingredient"});
        TIPS.put("hamburger_crimson_fungus", new String[]{null, "tooltip.createfood.crimson_fungus_ingredient"});
        TIPS.put("hamburger_lettuce", new String[]{null, "tooltip.createfood.lettuce_ingredient"});
        TIPS.put("hamburger_lettuce_tomato", new String[]{null, "tooltip.createfood.lettuce_ingredient", "tooltip.createfood.tomato_ingredient"});
        TIPS.put("hamburger_onion", new String[]{null, "tooltip.createfood.onion_ingredient"});
        TIPS.put("hamburger_onion_bacon", new String[]{null, "tooltip.createfood.onion_ingredient", "tooltip.createfood.bacon_ingredient"});
        TIPS.put("hamburger_onion_bacon_lettuce", new String[]{null, "tooltip.createfood.onion_ingredient", "tooltip.createfood.bacon_ingredient", "tooltip.createfood.lettuce_ingredient"});
        TIPS.put("hamburger_onion_lettuce", new String[]{null, "tooltip.createfood.onion_ingredient", "tooltip.createfood.lettuce_ingredient"});
        TIPS.put("hamburger_peanut_butter", new String[]{"peanut_butter", "tooltip.createfood.peanut_butter_ingredient"});
        TIPS.put("hamburger_peanut_butter_bacon", new String[]{"peanut_butter", "tooltip.createfood.peanut_butter_ingredient", "tooltip.createfood.bacon_ingredient"});
        TIPS.put("hamburger_tomato", new String[]{null, "tooltip.createfood.tomato_ingredient"});
        TIPS.put("hamburger_warped_fungus", new String[]{null, "tooltip.createfood.warped_fungus_ingredient"});
        TIPS.put("honeyed_apple_slice", new String[]{null, "tooltip.createfood.honey_ingredient"});
        TIPS.put("honeyed_berries", new String[]{null, "tooltip.createfood.honey_ingredient"});
        TIPS.put("honeyed_biscuit", new String[]{null, "tooltip.createfood.honey_ingredient"});
        TIPS.put("honeyed_chocolate_cupcake", new String[]{null, "tooltip.createfood.honey_ingredient"});
        TIPS.put("honeyed_chocolate_donut", new String[]{null, "tooltip.createfood.honey_ingredient"});
        TIPS.put("honeyed_chocolate_sweet_roll", new String[]{null, "tooltip.createfood.honey_ingredient"});
        TIPS.put("honeyed_cupcake", new String[]{null, "tooltip.createfood.honey_ingredient"});
        TIPS.put("honeyed_donut", new String[]{null, "tooltip.createfood.honey_ingredient"});
        TIPS.put("honeyed_mini_waffle", new String[]{null, "tooltip.createfood.honey_ingredient"});
        TIPS.put("honeyed_muffin", new String[]{null, "tooltip.createfood.honey_ingredient"});
        TIPS.put("honeyed_pretzel_stick", new String[]{null, "tooltip.createfood.honey_ingredient"});
        TIPS.put("honeyed_sweet_roll", new String[]{null, "tooltip.createfood.honey_ingredient"});
        TIPS.put("honeyed_toast", new String[]{null, "tooltip.createfood.honey_ingredient"});
        TIPS.put("ice_cream_sandwich_neapolitan", new String[]{null, "tooltip.createfood.chocolate_ice_cream_ingredient", "tooltip.createfood.ice_cream_ingredient", "tooltip.createfood.berry_ice_cream_ingredient"});
        TIPS.put("kelp_roll_beetroot", new String[]{null, "tooltip.createfood.beetroot_ingredient"});
        TIPS.put("kelp_roll_brown_mushroom", new String[]{null, "tooltip.createfood.brown_mushroom_ingredient"});
        TIPS.put("kelp_roll_crimson_fungus", new String[]{null, "tooltip.createfood.crimson_fungus_ingredient"});
        TIPS.put("kelp_roll_fish", new String[]{null, "tooltip.createfood.fish_ingredient"});
        TIPS.put("kelp_roll_lettuce", new String[]{null, "tooltip.createfood.lettuce_ingredient"});
        TIPS.put("kelp_roll_onion", new String[]{null, "tooltip.createfood.onion_ingredient"});
        TIPS.put("kelp_roll_red_mushroom", new String[]{null, "tooltip.createfood.red_mushroom_ingredient"});
        TIPS.put("kelp_roll_rice", new String[]{null, "tooltip.createfood.rice_ingredient"});
        TIPS.put("kelp_roll_slice_beetroot", new String[]{null, "tooltip.createfood.beetroot_ingredient"});
        TIPS.put("kelp_roll_slice_brown_mushroom", new String[]{null, "tooltip.createfood.brown_mushroom_ingredient"});
        TIPS.put("kelp_roll_slice_crimson_fungus", new String[]{null, "tooltip.createfood.crimson_fungus_ingredient"});
        TIPS.put("kelp_roll_slice_fish", new String[]{null, "tooltip.createfood.fish_ingredient"});
        TIPS.put("kelp_roll_slice_lettuce", new String[]{null, "tooltip.createfood.lettuce_ingredient"});
        TIPS.put("kelp_roll_slice_onion", new String[]{null, "tooltip.createfood.onion_ingredient"});
        TIPS.put("kelp_roll_slice_red_mushroom", new String[]{null, "tooltip.createfood.red_mushroom_ingredient"});
        TIPS.put("kelp_roll_slice_rice", new String[]{null, "tooltip.createfood.rice_ingredient"});
        TIPS.put("kelp_roll_slice_tomato", new String[]{null, "tooltip.createfood.tomato_ingredient"});
        TIPS.put("kelp_roll_slice_warped_fungus", new String[]{null, "tooltip.createfood.warped_fungus_ingredient"});
        TIPS.put("kelp_roll_tomato", new String[]{null, "tooltip.createfood.tomato_ingredient"});
        TIPS.put("kelp_roll_warped_fungus", new String[]{null, "tooltip.createfood.warped_fungus_ingredient"});
        TIPS.put("macaroni_bowl_bacon", new String[]{null, "tooltip.createfood.bacon_ingredient"});
        TIPS.put("macaroni_bowl_cheese", new String[]{null, "tooltip.createfood.cheese_ingredient"});
        TIPS.put("macaroni_bowl_cheese_bacon", new String[]{null, "tooltip.createfood.cheese_ingredient", "tooltip.createfood.bacon_ingredient"});
        TIPS.put("macaroni_bowl_cheese_sausage", new String[]{null, "tooltip.createfood.cheese_ingredient", "tooltip.createfood.sausage_ingredient"});
        TIPS.put("macaroni_bowl_sausage", new String[]{null, "tooltip.createfood.sausage_ingredient"});
        TIPS.put("marshmallow_butterscotch_fudge", new String[]{null, "tooltip.createfood.marshmallow_ingredient"});
        TIPS.put("marshmallow_caramel_fudge", new String[]{null, "tooltip.createfood.marshmallow_ingredient"});
        TIPS.put("marshmallow_chocolate", new String[]{null, "tooltip.createfood.marshmallow_ingredient"});
        TIPS.put("marshmallow_chocolate_fudge", new String[]{null, "tooltip.createfood.marshmallow_ingredient"});
        TIPS.put("marshmallow_coffee_toffee_fudge", new String[]{"coffee", "tooltip.createfood.marshmallow_ingredient"});
        TIPS.put("marshmallow_dark_chocolate", new String[]{null, "tooltip.createfood.marshmallow_ingredient"});
        TIPS.put("marshmallow_dark_chocolate_fudge", new String[]{null, "tooltip.createfood.marshmallow_ingredient"});
        TIPS.put("marshmallow_hot_chocolate_bottle", new String[]{null, "tooltip.createfood.marshmallow_ingredient"});
        TIPS.put("marshmallow_hot_dark_chocolate_bottle", new String[]{null, "tooltip.createfood.marshmallow_ingredient"});
        TIPS.put("marshmallow_hot_white_chocolate_bottle", new String[]{null, "tooltip.createfood.marshmallow_ingredient"});
        TIPS.put("marshmallow_toffee_fudge", new String[]{null, "tooltip.createfood.marshmallow_ingredient"});
        TIPS.put("marshmallow_white_chocolate", new String[]{null, "tooltip.createfood.marshmallow_ingredient"});
        TIPS.put("marshmallow_white_chocolate_fudge", new String[]{null, "tooltip.createfood.marshmallow_ingredient"});
        TIPS.put("mashed_potatoes_bowl_bacon", new String[]{null, "tooltip.createfood.bacon_ingredient"});
        TIPS.put("mashed_potatoes_bowl_cheese", new String[]{null, "tooltip.createfood.cheese_ingredient"});
        TIPS.put("mashed_potatoes_bowl_mushroom", new String[]{null, "tooltip.createfood.mushroom_ingredient"});
        TIPS.put("mashed_potatoes_bowl_sour_cream", new String[]{null, "tooltip.createfood.sour_cream_ingredient"});
        TIPS.put("melon_cream_cake_slice", new String[]{null, "tooltip.createfood.melon_cream_frosting_ingredient"});
        TIPS.put("melon_cream_chocolate", new String[]{null, "tooltip.createfood.melon_cream_frosting_ingredient"});
        TIPS.put("melon_cream_chocolate_cupcake", new String[]{null, "tooltip.createfood.melon_cream_frosting_ingredient"});
        TIPS.put("melon_cream_chocolate_donut", new String[]{null, "tooltip.createfood.melon_cream_frosting_ingredient"});
        TIPS.put("melon_cream_chocolate_pastry", new String[]{null, "tooltip.createfood.melon_cream_frosting_ingredient"});
        TIPS.put("melon_cream_chocolate_sweet_roll", new String[]{null, "tooltip.createfood.melon_cream_frosting_ingredient"});
        TIPS.put("melon_cream_cupcake", new String[]{null, "tooltip.createfood.melon_cream_frosting_ingredient"});
        TIPS.put("melon_cream_dark_chocolate", new String[]{null, "tooltip.createfood.melon_cream_frosting_ingredient"});
        TIPS.put("melon_cream_donut", new String[]{null, "tooltip.createfood.melon_cream_frosting_ingredient"});
        TIPS.put("melon_cream_frosting_piping_bag", new String[]{null, "tooltip.createfood.melon_cream_frosting_ingredient"});
        TIPS.put("melon_cream_mini_waffle", new String[]{null, "tooltip.createfood.melon_cream_frosting_ingredient"});
        TIPS.put("melon_cream_pastry", new String[]{null, "tooltip.createfood.melon_cream_frosting_ingredient"});
        TIPS.put("melon_cream_sweet_roll", new String[]{null, "tooltip.createfood.melon_cream_frosting_ingredient"});
        TIPS.put("melon_cream_white_chocolate", new String[]{null, "tooltip.createfood.melon_cream_frosting_ingredient"});
        TIPS.put("melon_ice_cream_sandwich", new String[]{null, "tooltip.createfood.melon_ice_cream_ingredient"});
        TIPS.put("melon_jam_chocolate_donut", new String[]{null, "tooltip.createfood.melon_jam_ingredient"});
        TIPS.put("melon_jam_donut", new String[]{null, "tooltip.createfood.melon_jam_ingredient"});
        TIPS.put("melon_jam_sandwich", new String[]{null, "tooltip.createfood.melon_jam_ingredient"});
        TIPS.put("minced_dragon", new String[]{"dragon_meat"});
        TIPS.put("mini_chocolate_pie_graham_cracker", new String[]{null, "tooltip.createfood.graham_cracker_pie_crust_ingredient"});
        TIPS.put("mini_cream_pie_chocolate_graham_cracker", new String[]{null, "tooltip.createfood.chocolate_graham_cracker_pie_crust_ingredient"});
        TIPS.put("mini_cream_pie_graham_cracker", new String[]{null, "tooltip.createfood.graham_cracker_pie_crust_ingredient"});
        TIPS.put("mixed_salad_beetroot_carrot", new String[]{null, "tooltip.createfood.beetroot_ingredient", "tooltip.createfood.carrot_ingredient"});
        TIPS.put("mushroom_bacon_pizza_slice", new String[]{null, "tooltip.createfood.mushroom_ingredient", "tooltip.createfood.bacon_ingredient"});
        TIPS.put("mushroom_burrito_rice", new String[]{null, "tooltip.createfood.mushroom_ingredient", "tooltip.createfood.rice_ingredient"});
        TIPS.put("mushroom_calzone", new String[]{null, "tooltip.createfood.cheese_ingredient", "tooltip.createfood.mushroom_ingredient"});
        TIPS.put("mushroom_fish_pizza_slice", new String[]{null, "tooltip.createfood.mushroom_ingredient", "tooltip.createfood.fish_ingredient"});
        TIPS.put("mushroom_onion_pizza_slice", new String[]{null, "tooltip.createfood.mushroom_ingredient", "tooltip.createfood.onion_ingredient"});
        TIPS.put("mushroom_pizza_slice", new String[]{null, "tooltip.createfood.mushroom_ingredient"});
        TIPS.put("mushroom_rice_bowl", new String[]{null, "tooltip.createfood.kelp_ingredient"});
        TIPS.put("mushroom_taco", new String[]{null, "tooltip.createfood.mushroom_ingredient"});
        TIPS.put("mushroom_taco_lettuce", new String[]{null, "tooltip.createfood.mushroom_ingredient", "tooltip.createfood.lettuce_ingredient"});
        TIPS.put("mushroom_taco_lettuce_taco_sauce", new String[]{null, "tooltip.createfood.mushroom_ingredient", "tooltip.createfood.lettuce_ingredient", "tooltip.createfood.taco_sauce_ingredient"});
        TIPS.put("mushroom_wrap_lettuce_potato", new String[]{null, "tooltip.createfood.mushroom_ingredient", "tooltip.createfood.lettuce_ingredient", "tooltip.createfood.potato_ingredient"});
        TIPS.put("mutton_burrito_rice", new String[]{null, "tooltip.createfood.mutton_ingredient", "tooltip.createfood.rice_ingredient"});
        TIPS.put("mutton_calzone", new String[]{null, "tooltip.createfood.cheese_ingredient", "tooltip.createfood.mutton_ingredient"});
        TIPS.put("mutton_sandwich", new String[]{null, "tooltip.createfood.mutton_ingredient"});
        TIPS.put("mutton_sandwich_beetroot", new String[]{null, "tooltip.createfood.mutton_ingredient", "tooltip.createfood.beetroot_ingredient"});
        TIPS.put("mutton_taco", new String[]{null, "tooltip.createfood.mutton_ingredient"});
        TIPS.put("mutton_taco_lettuce", new String[]{null, "tooltip.createfood.mutton_ingredient", "tooltip.createfood.lettuce_ingredient"});
        TIPS.put("mutton_taco_lettuce_taco_sauce", new String[]{null, "tooltip.createfood.mutton_ingredient", "tooltip.createfood.lettuce_ingredient", "tooltip.createfood.taco_sauce_ingredient"});
        TIPS.put("mutton_wrap_lettuce_tomato", new String[]{null, "tooltip.createfood.mutton_ingredient", "tooltip.createfood.lettuce_ingredient", "tooltip.createfood.tomato_ingredient"});
        TIPS.put("nacho_bowl_beef", new String[]{null, "tooltip.createfood.beef_ingredient"});
        TIPS.put("nacho_bowl_beef_taco_sauce", new String[]{null, "tooltip.createfood.beef_ingredient", "tooltip.createfood.taco_sauce_ingredient"});
        TIPS.put("nacho_bowl_sour_cream", new String[]{null, "tooltip.createfood.sour_cream_ingredient"});
        TIPS.put("nacho_bowl_taco_sauce", new String[]{null, "tooltip.createfood.taco_sauce_ingredient"});
        TIPS.put("onion_bacon_pizza_slice", new String[]{null, "tooltip.createfood.onion_ingredient", "tooltip.createfood.bacon_ingredient"});
        TIPS.put("onion_calzone", new String[]{null, "tooltip.createfood.cheese_ingredient", "tooltip.createfood.onion_ingredient"});
        TIPS.put("onion_pizza_slice", new String[]{null, "tooltip.createfood.onion_ingredient"});
        TIPS.put("pasta_plate_beef_meatballs", new String[]{null, "tooltip.createfood.beef_meatballs_ingredient"});
        TIPS.put("pasta_plate_butter", new String[]{null, "tooltip.createfood.butter_ingredient"});
        TIPS.put("pasta_plate_cheese", new String[]{null, "tooltip.createfood.cheese_ingredient"});
        TIPS.put("pasta_plate_cheese_tomato_sauce", new String[]{null, "tooltip.createfood.tomato_sauce_ingredient", "tooltip.createfood.cheese_ingredient"});
        TIPS.put("pasta_plate_chicken_cut", new String[]{null, "tooltip.createfood.chicken_ingredient"});
        TIPS.put("pasta_plate_chicken_cut_tomato_sauce", new String[]{null, "tooltip.createfood.tomato_sauce_ingredient", "tooltip.createfood.chicken_ingredient"});
        TIPS.put("pasta_plate_eggplant", new String[]{"eggplant", "tooltip.createfood.eggplant_ingredient"});
        TIPS.put("pasta_plate_endermite_meatballs", new String[]{"endermite_meat", "tooltip.createfood.endermite_meatballs_ingredient"});
        TIPS.put("pasta_plate_endermite_meatballs_tomato_sauce", new String[]{"endermite_meat", "tooltip.createfood.tomato_sauce_ingredient", "tooltip.createfood.endermite_meatballs_ingredient"});
        TIPS.put("pasta_plate_fish", new String[]{null, "tooltip.createfood.fish_ingredient"});
        TIPS.put("pasta_plate_fish_tomato_sauce", new String[]{null, "tooltip.createfood.tomato_sauce_ingredient", "tooltip.createfood.fish_ingredient"});
        TIPS.put("pasta_plate_mushroom", new String[]{null, "tooltip.createfood.mushroom_ingredient"});
        TIPS.put("pasta_plate_mushroom_tomato_sauce", new String[]{null, "tooltip.createfood.mushroom_ingredient", "tooltip.createfood.tomato_sauce_ingredient"});
        TIPS.put("pasta_plate_mutton_chop", new String[]{null, "tooltip.createfood.mutton_ingredient"});
        TIPS.put("pasta_plate_pork_meatballs", new String[]{null, "tooltip.createfood.pork_meatballs_ingredient"});
        TIPS.put("pasta_plate_pork_meatballs_tomato_sauce", new String[]{null, "tooltip.createfood.tomato_sauce_ingredient", "tooltip.createfood.pork_meatballs_ingredient"});
        TIPS.put("pasta_plate_rabbit_meatballs", new String[]{null, "tooltip.createfood.rabbit_meatballs_ingredient"});
        TIPS.put("pasta_plate_rabbit_meatballs_tomato_sauce", new String[]{null, "tooltip.createfood.tomato_sauce_ingredient", "tooltip.createfood.rabbit_meatballs_ingredient"});
        TIPS.put("pasta_plate_slime", new String[]{null, "tooltip.createfood.slime_ingredient"});
        TIPS.put("pasta_plate_slimeballs", new String[]{null, "tooltip.createfood.slimeballs_ingredient"});
        TIPS.put("pasta_plate_squid_ink", new String[]{null, "tooltip.createfood.squid_ink_ingredient"});
        TIPS.put("pasta_plate_strider_meatballs", new String[]{"strider_meat", "tooltip.createfood.strider_meatballs_ingredient"});
        TIPS.put("pasta_plate_strider_meatballs_tomato_sauce", new String[]{"strider_meat", "tooltip.createfood.tomato_sauce_ingredient", "tooltip.createfood.strider_meatballs_ingredient"});
        TIPS.put("pasta_plate_tomato_sauce", new String[]{null, "tooltip.createfood.tomato_sauce_ingredient"});
        TIPS.put("peanut_butter_apple_jam_sandwich", new String[]{"peanut_butter", "tooltip.createfood.peanut_butter_ingredient", "tooltip.createfood.apple_jam_ingredient"});
        TIPS.put("peanut_butter_chorus_fruit_jam_sandwich", new String[]{"peanut_butter", "tooltip.createfood.peanut_butter_ingredient", "tooltip.createfood.chorus_fruit_jam_ingredient"});
        TIPS.put("peanut_butter_melon_jam_sandwich", new String[]{"peanut_butter", "tooltip.createfood.peanut_butter_ingredient", "tooltip.createfood.melon_jam_ingredient"});
        TIPS.put("pork_burrito_rice", new String[]{null, "tooltip.createfood.pork_ingredient", "tooltip.createfood.rice_ingredient"});
        TIPS.put("pork_meatball_sandwich", new String[]{null, "tooltip.createfood.pork_meatballs_ingredient"});
        TIPS.put("pork_taco", new String[]{null, "tooltip.createfood.pork_ingredient"});
        TIPS.put("pork_taco_lettuce", new String[]{null, "tooltip.createfood.pork_ingredient", "tooltip.createfood.lettuce_ingredient"});
        TIPS.put("pork_taco_lettuce_taco_sauce", new String[]{null, "tooltip.createfood.pork_ingredient", "tooltip.createfood.lettuce_ingredient", "tooltip.createfood.taco_sauce_ingredient"});
        TIPS.put("pork_wrap_onion_lettuce", new String[]{null, "tooltip.createfood.pork_ingredient", "tooltip.createfood.onion_ingredient", "tooltip.createfood.lettuce_ingredient"});
        TIPS.put("potato_cream_soup_bowl_cheese", new String[]{null, "tooltip.createfood.cheese_ingredient"});
        TIPS.put("pumpernickel_toast_cream_cheese", new String[]{null, "tooltip.createfood.cream_cheese_ingredient"});
        TIPS.put("pumpernickel_toast_cream_cheese_beetroot", new String[]{null, "tooltip.createfood.cream_cheese_ingredient", "tooltip.createfood.beetroot_ingredient"});
        TIPS.put("pumpernickel_toast_cream_cheese_beetroot_honey", new String[]{null, "tooltip.createfood.cream_cheese_ingredient", "tooltip.createfood.beetroot_ingredient", "tooltip.createfood.honey_ingredient"});
        TIPS.put("pumpernickel_toast_cream_cheese_mushroom", new String[]{null, "tooltip.createfood.cream_cheese_ingredient", "tooltip.createfood.mushroom_ingredient"});
        TIPS.put("pumpernickel_toast_cream_cheese_mushroom_bacon", new String[]{null, "tooltip.createfood.cream_cheese_ingredient", "tooltip.createfood.mushroom_ingredient", "tooltip.createfood.bacon_ingredient"});
        TIPS.put("pumpernickel_toast_cream_cheese_salmon", new String[]{null, "tooltip.createfood.cream_cheese_ingredient", "tooltip.createfood.salmon_ingredient"});
        TIPS.put("pumpernickel_toast_cream_cheese_salmon_onion", new String[]{null, "tooltip.createfood.cream_cheese_ingredient", "tooltip.createfood.salmon_ingredient", "tooltip.createfood.onion_ingredient"});
        TIPS.put("rabbit_burrito_rice", new String[]{null, "tooltip.createfood.rabbit_ingredient", "tooltip.createfood.rice_ingredient"});
        TIPS.put("rabbit_calzone", new String[]{null, "tooltip.createfood.cheese_ingredient", "tooltip.createfood.rabbit_ingredient"});
        TIPS.put("rabbit_meatball_sandwich", new String[]{null, "tooltip.createfood.rabbit_meatballs_ingredient"});
        TIPS.put("rabbit_taco", new String[]{null, "tooltip.createfood.rabbit_ingredient"});
        TIPS.put("rabbit_taco_lettuce", new String[]{null, "tooltip.createfood.rabbit_ingredient", "tooltip.createfood.lettuce_ingredient"});
        TIPS.put("rabbit_taco_lettuce_taco_sauce", new String[]{null, "tooltip.createfood.rabbit_ingredient", "tooltip.createfood.lettuce_ingredient", "tooltip.createfood.taco_sauce_ingredient"});
        TIPS.put("rabbit_wrap_onion_potato", new String[]{null, "tooltip.createfood.rabbit_ingredient", "tooltip.createfood.onion_ingredient", "tooltip.createfood.potato_ingredient"});
        TIPS.put("raw_bacon_calzone", new String[]{null, "tooltip.createfood.cheese_ingredient", "tooltip.createfood.bacon_ingredient"});
        TIPS.put("raw_beef_calzone", new String[]{null, "tooltip.createfood.cheese_ingredient", "tooltip.createfood.beef_ingredient"});
        TIPS.put("raw_berry_cookie", new String[]{null, "tooltip.createfood.berry_ingredient"});
        TIPS.put("raw_butterscotch_chip_chocolate_cookie", new String[]{null, "tooltip.createfood.butterscotch_chips_ingredient"});
        TIPS.put("raw_butterscotch_chip_cookie", new String[]{null, "tooltip.createfood.butterscotch_chips_ingredient"});
        TIPS.put("raw_caramel_chip_chocolate_cookie", new String[]{null, "tooltip.createfood.caramel_chips_ingredient"});
        TIPS.put("raw_caramel_chip_cookie", new String[]{null, "tooltip.createfood.caramel_chips_ingredient"});
        TIPS.put("raw_cheese_calzone", new String[]{null, "tooltip.createfood.cheese_ingredient"});
        TIPS.put("raw_chicken_calzone", new String[]{null, "tooltip.createfood.cheese_ingredient", "tooltip.createfood.chicken_ingredient"});
        TIPS.put("raw_chocolate_chip_chocolate_cookie", new String[]{null, "tooltip.createfood.chocolate_chips_ingredient"});
        TIPS.put("raw_chocolate_chip_cookie", new String[]{null, "tooltip.createfood.chocolate_chips_ingredient"});
        TIPS.put("raw_chorus_fruit_cookie", new String[]{null, "tooltip.createfood.chorus_fruit_ingredient"});
        TIPS.put("raw_cinnamon_sweet_roll_base", new String[]{"cinnamon"});
        TIPS.put("raw_dark_chocolate_chip_chocolate_cookie", new String[]{null, "tooltip.createfood.dark_chocolate_chips_ingredient"});
        TIPS.put("raw_dark_chocolate_chip_cookie", new String[]{null, "tooltip.createfood.dark_chocolate_chips_ingredient"});
        TIPS.put("raw_endermite_meatball", new String[]{"endermite_meat"});
        TIPS.put("raw_fish_calzone", new String[]{null, "tooltip.createfood.cheese_ingredient", "tooltip.createfood.fish_ingredient"});
        TIPS.put("raw_flesh_cookie", new String[]{"raw_flesh_cookie", "tooltip.createfood.flesh_ingredient"});
        TIPS.put("raw_ginger_cookie", new String[]{"raw_ginger_cookie", "tooltip.createfood.ginger_ingredient"});
        TIPS.put("raw_glow_berry_cookie", new String[]{null, "tooltip.createfood.glow_berry_ingredient"});
        TIPS.put("raw_green_tea_cookie", new String[]{"raw_green_tea_cookie"});
        TIPS.put("raw_mini_chocolate_pie_graham_cracker", new String[]{null, "tooltip.createfood.graham_cracker_pie_crust_ingredient"});
        TIPS.put("raw_mini_cream_pie_chocolate_graham_cracker", new String[]{null, "tooltip.createfood.chocolate_graham_cracker_pie_crust_ingredient"});
        TIPS.put("raw_mini_cream_pie_graham_cracker", new String[]{null, "tooltip.createfood.graham_cracker_pie_crust_ingredient"});
        TIPS.put("raw_mushroom_calzone", new String[]{null, "tooltip.createfood.cheese_ingredient", "tooltip.createfood.mushroom_ingredient"});
        TIPS.put("raw_mutton_calzone", new String[]{null, "tooltip.createfood.cheese_ingredient", "tooltip.createfood.mutton_ingredient"});
        TIPS.put("raw_onion_calzone", new String[]{null, "tooltip.createfood.cheese_ingredient", "tooltip.createfood.onion_ingredient"});
        TIPS.put("raw_rabbit_calzone", new String[]{null, "tooltip.createfood.cheese_ingredient", "tooltip.createfood.rabbit_ingredient"});
        TIPS.put("raw_sausage_calzone", new String[]{null, "tooltip.createfood.cheese_ingredient", "tooltip.createfood.sausage_ingredient"});
        TIPS.put("raw_sausage_roll_cheese", new String[]{null, "tooltip.createfood.cheese_ingredient"});
        TIPS.put("raw_snickerdoodle", new String[]{"raw_snickerdoodle"});
        TIPS.put("raw_soul_berry_cookie", new String[]{"raw_flesh_cookie", "tooltip.createfood.soul_berry_ingredient"});
        TIPS.put("raw_spicy_sausage_roll_cheese", new String[]{null, "tooltip.createfood.cheese_ingredient"});
        TIPS.put("raw_spider_eye_cookie", new String[]{"raw_flesh_cookie", "tooltip.createfood.spider_eye_ingredient"});
        TIPS.put("raw_strider_meatball", new String[]{"strider_meat"});
        TIPS.put("raw_sugar_cookie", new String[]{"raw_sugar_cookie"});
        TIPS.put("raw_toffee_chip_chocolate_cookie", new String[]{null, "tooltip.createfood.toffee_chips_ingredient"});
        TIPS.put("raw_toffee_chip_cookie", new String[]{null, "tooltip.createfood.toffee_chips_ingredient"});
        TIPS.put("raw_ube_cookie", new String[]{"ube"});
        TIPS.put("raw_white_chocolate_chip_chocolate_cookie", new String[]{null, "tooltip.createfood.white_chocolate_chips_ingredient"});
        TIPS.put("raw_white_chocolate_chip_cookie", new String[]{null, "tooltip.createfood.white_chocolate_chips_ingredient"});
        TIPS.put("sausage_bacon_pizza_slice", new String[]{null, "tooltip.createfood.sausage_ingredient", "tooltip.createfood.bacon_ingredient"});
        TIPS.put("sausage_biscuit_bacon", new String[]{null, "tooltip.createfood.bacon_ingredient"});
        TIPS.put("sausage_biscuit_cheese", new String[]{null, "tooltip.createfood.cheese_ingredient"});
        TIPS.put("sausage_biscuit_cheese_bacon", new String[]{null, "tooltip.createfood.cheese_ingredient", "tooltip.createfood.bacon_ingredient"});
        TIPS.put("sausage_biscuit_cheese_fried_egg", new String[]{null, "tooltip.createfood.cheese_ingredient", "tooltip.createfood.fried_egg_ingredient"});
        TIPS.put("sausage_biscuit_cheese_fried_egg_bacon", new String[]{null, "tooltip.createfood.cheese_ingredient", "tooltip.createfood.fried_egg_ingredient", "tooltip.createfood.bacon_ingredient"});
        TIPS.put("sausage_biscuit_fried_egg", new String[]{null, "tooltip.createfood.fried_egg_ingredient"});
        TIPS.put("sausage_biscuit_fried_egg_bacon", new String[]{null, "tooltip.createfood.fried_egg_ingredient", "tooltip.createfood.bacon_ingredient"});
        TIPS.put("sausage_biscuit_sandwich_bacon", new String[]{null, "tooltip.createfood.bacon_ingredient"});
        TIPS.put("sausage_biscuit_sandwich_cheese", new String[]{null, "tooltip.createfood.cheese_ingredient"});
        TIPS.put("sausage_biscuit_sandwich_cheese_bacon", new String[]{null, "tooltip.createfood.cheese_ingredient", "tooltip.createfood.bacon_ingredient"});
        TIPS.put("sausage_biscuit_sandwich_cheese_fried_egg", new String[]{null, "tooltip.createfood.cheese_ingredient", "tooltip.createfood.fried_egg_ingredient"});
        TIPS.put("sausage_biscuit_sandwich_cheese_fried_egg_bacon", new String[]{null, "tooltip.createfood.cheese_ingredient", "tooltip.createfood.fried_egg_ingredient", "tooltip.createfood.bacon_ingredient"});
        TIPS.put("sausage_biscuit_sandwich_fried_egg", new String[]{null, "tooltip.createfood.fried_egg_ingredient"});
        TIPS.put("sausage_biscuit_sandwich_fried_egg_bacon", new String[]{null, "tooltip.createfood.fried_egg_ingredient", "tooltip.createfood.bacon_ingredient"});
        TIPS.put("sausage_calzone", new String[]{null, "tooltip.createfood.cheese_ingredient", "tooltip.createfood.sausage_ingredient"});
        TIPS.put("sausage_fish_pizza_slice", new String[]{null, "tooltip.createfood.sausage_ingredient", "tooltip.createfood.fish_ingredient"});
        TIPS.put("sausage_mushroom_pizza_slice", new String[]{null, "tooltip.createfood.sausage_ingredient", "tooltip.createfood.mushroom_ingredient"});
        TIPS.put("sausage_onion_pizza_slice", new String[]{null, "tooltip.createfood.sausage_ingredient", "tooltip.createfood.onion_ingredient"});
        TIPS.put("sausage_pizza_slice", new String[]{null, "tooltip.createfood.sausage_ingredient"});
        TIPS.put("sausage_roll_cheese", new String[]{null, "tooltip.createfood.cheese_ingredient"});
        TIPS.put("scone_apple_jam", new String[]{null, "tooltip.createfood.apple_jam_ingredient"});
        TIPS.put("scone_berry_jam", new String[]{null, "tooltip.createfood.berry_jam_ingredient"});
        TIPS.put("scone_butter", new String[]{null, "tooltip.createfood.butter_ingredient"});
        TIPS.put("scone_chorus_fruit_jam", new String[]{null, "tooltip.createfood.chorus_fruit_jam_ingredient"});
        TIPS.put("scone_glow_berry_jam", new String[]{null, "tooltip.createfood.glow_berry_jam_ingredient"});
        TIPS.put("scone_melon_jam", new String[]{null, "tooltip.createfood.melon_jam_ingredient"});
        TIPS.put("scrambled_eggs_plate_bacon", new String[]{null, "tooltip.createfood.bacon_ingredient"});
        TIPS.put("scrambled_eggs_plate_cheese", new String[]{null, "tooltip.createfood.cheese_ingredient"});
        TIPS.put("scrambled_eggs_plate_mushroom", new String[]{null, "tooltip.createfood.mushroom_ingredient"});
        TIPS.put("scrambled_eggs_plate_onion", new String[]{null, "tooltip.createfood.onion_ingredient"});
        TIPS.put("scrambled_eggs_plate_sausage", new String[]{null, "tooltip.createfood.sausage_ingredient"});
        TIPS.put("scrambled_eggs_plate_tomato", new String[]{null, "tooltip.createfood.tomato_ingredient"});
        TIPS.put("scrambled_egg_sandwich", new String[]{null, "tooltip.createfood.scrambled_egg_ingredient"});
        TIPS.put("sliced_brown_mushroom_salt", new String[]{null, "tooltip.createfood.salt_ingredient"});
        TIPS.put("sliced_crimson_fungus_salt", new String[]{null, "tooltip.createfood.salt_ingredient"});
        TIPS.put("sliced_red_mushroom_salt", new String[]{null, "tooltip.createfood.salt_ingredient"});
        TIPS.put("sliced_warped_fungus_salt", new String[]{null, "tooltip.createfood.salt_ingredient"});
        TIPS.put("small_endermite_meatballs", new String[]{"endermite_meat"});
        TIPS.put("small_strider_meatballs", new String[]{"strider_meat"});
        TIPS.put("spicy_sausage_roll_cheese", new String[]{null, "tooltip.createfood.cheese_ingredient"});
        TIPS.put("strider_meatball", new String[]{"strider_meat"});
        TIPS.put("strider_meatball_sandwich", new String[]{"strider_meat", "tooltip.createfood.strider_meatballs_ingredient"});
        TIPS.put("toffee_apple", new String[]{null, "tooltip.createfood.toffee_ingredient"});
        TIPS.put("toffee_apple_slice", new String[]{null, "tooltip.createfood.toffee_ingredient"});
        TIPS.put("toffee_berries", new String[]{null, "tooltip.createfood.toffee_ingredient"});
        TIPS.put("toffee_chip_chocolate_cookie", new String[]{null, "tooltip.createfood.toffee_chips_ingredient"});
        TIPS.put("toffee_chip_chocolate_milkshake_bottle", new String[]{null, "tooltip.createfood.toffee_chips_ingredient"});
        TIPS.put("toffee_chip_cookie", new String[]{null, "tooltip.createfood.toffee_chips_ingredient"});
        TIPS.put("toffee_chip_ice_cream_cone", new String[]{null, "tooltip.createfood.toffee_chips_ingredient"});
        TIPS.put("toffee_chip_milkshake_bottle", new String[]{null, "tooltip.createfood.toffee_chips_ingredient"});
        TIPS.put("toffee_chip_mini_waffle", new String[]{null, "tooltip.createfood.toffee_chips_ingredient"});
        TIPS.put("toffee_chip_muffin", new String[]{null, "tooltip.createfood.toffee_chips_ingredient"});
        TIPS.put("toffee_chocolate", new String[]{null, "tooltip.createfood.toffee_ingredient"});
        TIPS.put("toffee_chocolate_pastry", new String[]{null, "tooltip.createfood.toffee_ingredient"});
        TIPS.put("toffee_chocolate_sweet_roll", new String[]{null, "tooltip.createfood.toffee_ingredient"});
        TIPS.put("toffee_dark_chocolate", new String[]{null, "tooltip.createfood.toffee_ingredient"});
        TIPS.put("toffee_fudge_ice_cream_bowl", new String[]{null, "tooltip.createfood.toffee_fudge_ingredient"});
        TIPS.put("toffee_marshmallow_stick", new String[]{null, "tooltip.createfood.toffee_ingredient"});
        TIPS.put("toffee_pastry", new String[]{null, "tooltip.createfood.toffee_ingredient"});
        TIPS.put("toffee_pretzel_stick", new String[]{null, "tooltip.createfood.toffee_ingredient"});
        TIPS.put("toffee_sweet_roll", new String[]{null, "tooltip.createfood.toffee_ingredient"});
        TIPS.put("toffee_toast", new String[]{null, "tooltip.createfood.toffee_ingredient"});
        TIPS.put("toffee_white_chocolate", new String[]{null, "tooltip.createfood.toffee_ingredient"});
        TIPS.put("tortilla_chip_bowl", new String[]{"corn"});
        TIPS.put("ube_cream_frosting_bottle", new String[]{"ube"});
        TIPS.put("ube_cream_frosting_piping_bag", new String[]{"ube", "tooltip.createfood.ube_cream_frosting_ingredient"});
        TIPS.put("ube_cream_ube_cake_slice", new String[]{"ube", "tooltip.createfood.ube_cream_frosting_ingredient"});
        TIPS.put("ube_cream_ube_cupcake", new String[]{"ube", "tooltip.createfood.ube_cream_frosting_ingredient"});
        TIPS.put("ube_cupcake_base", new String[]{"ube"});
        TIPS.put("ube_sugar_dough", new String[]{"ube"});
        TIPS.put("vegetable_sandwich_beetroot_lettuce", new String[]{null, "tooltip.createfood.beetroot_ingredient", "tooltip.createfood.lettuce_ingredient"});
        TIPS.put("vegetable_sandwich_lettuce_tomato", new String[]{null, "tooltip.createfood.lettuce_ingredient", "tooltip.createfood.tomato_ingredient"});
        TIPS.put("vegetable_wrap_onion_lettuce_tomato", new String[]{null, "tooltip.createfood.onion_ingredient", "tooltip.createfood.lettuce_ingredient", "tooltip.createfood.tomato_ingredient"});
        TIPS.put("white_chocolate_apple", new String[]{null, "tooltip.createfood.white_chocolate_ingredient"});
        TIPS.put("white_chocolate_apple_slice", new String[]{null, "tooltip.createfood.white_chocolate_ingredient"});
        TIPS.put("white_chocolate_berries", new String[]{null, "tooltip.createfood.white_chocolate_ingredient"});
        TIPS.put("white_chocolate_chip_chocolate_cookie", new String[]{null, "tooltip.createfood.white_chocolate_chips_ingredient"});
        TIPS.put("white_chocolate_chip_chocolate_milkshake_bottle", new String[]{null, "tooltip.createfood.white_chocolate_chips_ingredient"});
        TIPS.put("white_chocolate_chip_cookie", new String[]{null, "tooltip.createfood.white_chocolate_chips_ingredient"});
        TIPS.put("white_chocolate_chip_ice_cream_cone", new String[]{null, "tooltip.createfood.white_chocolate_chips_ingredient"});
        TIPS.put("white_chocolate_chip_milkshake_bottle", new String[]{null, "tooltip.createfood.white_chocolate_chips_ingredient"});
        TIPS.put("white_chocolate_chip_mini_waffle", new String[]{null, "tooltip.createfood.white_chocolate_chips_ingredient"});
        TIPS.put("white_chocolate_chip_muffin", new String[]{null, "tooltip.createfood.white_chocolate_chips_ingredient"});
        TIPS.put("white_chocolate_chocolate_pastry", new String[]{null, "tooltip.createfood.white_chocolate_ingredient"});
        TIPS.put("white_chocolate_marshmallow_stick", new String[]{null, "tooltip.createfood.white_chocolate_ingredient"});
        TIPS.put("white_chocolate_pastry", new String[]{null, "tooltip.createfood.white_chocolate_ingredient"});
        TIPS.put("white_chocolate_pretzel_stick", new String[]{null, "tooltip.createfood.white_chocolate_ingredient"});
        TIPS.put("white_chocolate_toast", new String[]{null, "tooltip.createfood.white_chocolate_ingredient"});
        TIPS.put("yogurt_bowl_berry", new String[]{null, "tooltip.createfood.berry_ingredient"});
        TIPS.put("yogurt_bowl_chorus_fruit", new String[]{null, "tooltip.createfood.chorus_fruit_ingredient"});
        TIPS.put("yogurt_bowl_glow_berry", new String[]{null, "tooltip.createfood.glow_berry_ingredient"});
        TIPS.put("yogurt_bowl_honey", new String[]{null, "tooltip.createfood.honey_ingredient"});

        // ── block items ───────────────────────────────────────────────────────

        // cakes
        TIPS.put("apple_cream_cake",                          new String[]{null, "tooltip.createfood.apple_cream_frosting_ingredient"});
        TIPS.put("berry_cream_cake",                          new String[]{null, "tooltip.createfood.berry_cream_frosting_ingredient"});
        TIPS.put("berry_cream_cake_chorus_fruit",             new String[]{null, "tooltip.createfood.berry_cream_frosting_ingredient", "tooltip.createfood.chorus_fruit_ingredient"});
        TIPS.put("berry_cream_cake_glow_berry",               new String[]{null, "tooltip.createfood.berry_cream_frosting_ingredient", "tooltip.createfood.glow_berry_ingredient"});
        TIPS.put("berry_cream_cake_sweet_berry",              new String[]{null, "tooltip.createfood.berry_cream_frosting_ingredient", "tooltip.createfood.berry_ingredient"});
        TIPS.put("chocolate_cream_cake",                      new String[]{null, "tooltip.createfood.chocolate_cream_frosting_ingredient"});
        TIPS.put("chocolate_cream_cake_butterscotch",         new String[]{null, "tooltip.createfood.chocolate_cream_frosting_ingredient", "tooltip.createfood.butterscotch_chips_ingredient"});
        TIPS.put("chocolate_cream_cake_caramel",              new String[]{null, "tooltip.createfood.chocolate_cream_frosting_ingredient", "tooltip.createfood.caramel_chips_ingredient"});
        TIPS.put("chocolate_cream_cake_chocolate",            new String[]{null, "tooltip.createfood.chocolate_cream_frosting_ingredient", "tooltip.createfood.chocolate_chips_ingredient"});
        TIPS.put("chocolate_cream_cake_dark_chocolate",       new String[]{null, "tooltip.createfood.chocolate_cream_frosting_ingredient", "tooltip.createfood.dark_chocolate_chips_ingredient"});
        TIPS.put("chocolate_cream_cake_toffee",               new String[]{null, "tooltip.createfood.chocolate_cream_frosting_ingredient", "tooltip.createfood.toffee_chips_ingredient"});
        TIPS.put("chocolate_cream_cake_white_chocolate",      new String[]{null, "tooltip.createfood.chocolate_cream_frosting_ingredient", "tooltip.createfood.white_chocolate_chips_ingredient"});
        TIPS.put("chocolate_cream_chocolate_cake",            new String[]{null, "tooltip.createfood.chocolate_cream_frosting_ingredient"});
        TIPS.put("chorus_fruit_cream_cake",                   new String[]{null, "tooltip.createfood.chorus_fruit_cream_frosting_ingredient"});
        TIPS.put("chorus_fruit_cream_cake_chorus_fruit",      new String[]{null, "tooltip.createfood.chorus_fruit_cream_frosting_ingredient", "tooltip.createfood.chorus_fruit_ingredient"});
        TIPS.put("chorus_fruit_cream_cake_glow_berry",        new String[]{null, "tooltip.createfood.chorus_fruit_cream_frosting_ingredient", "tooltip.createfood.glow_berry_ingredient"});
        TIPS.put("chorus_fruit_cream_cake_sweet_berry",       new String[]{null, "tooltip.createfood.chorus_fruit_cream_frosting_ingredient", "tooltip.createfood.berry_ingredient"});
        TIPS.put("cream_cake",                                new String[]{null, "tooltip.createfood.cream_frosting_ingredient"});
        TIPS.put("cream_cake_chorus_fruit",                   new String[]{null, "tooltip.createfood.cream_frosting_ingredient", "tooltip.createfood.chorus_fruit_ingredient"});
        TIPS.put("cream_cake_glow_berry",                     new String[]{null, "tooltip.createfood.cream_frosting_ingredient", "tooltip.createfood.glow_berry_ingredient"});
        TIPS.put("cream_chocolate_cake",                      new String[]{null, "tooltip.createfood.cream_frosting_ingredient"});
        TIPS.put("glow_berry_cream_cake",                     new String[]{null, "tooltip.createfood.glow_berry_cream_frosting_ingredient"});
        TIPS.put("glow_berry_cream_cake_chorus_fruit",        new String[]{null, "tooltip.createfood.glow_berry_cream_frosting_ingredient", "tooltip.createfood.chorus_fruit_ingredient"});
        TIPS.put("glow_berry_cream_cake_glow_berry",          new String[]{null, "tooltip.createfood.glow_berry_cream_frosting_ingredient", "tooltip.createfood.glow_berry_ingredient"});
        TIPS.put("glow_berry_cream_cake_sweet_berry",         new String[]{null, "tooltip.createfood.glow_berry_cream_frosting_ingredient", "tooltip.createfood.berry_ingredient"});
        TIPS.put("melon_cream_cake",                          new String[]{null, "tooltip.createfood.melon_cream_frosting_ingredient"});
        TIPS.put("ube_cake_base",                             new String[]{"ube"});
        TIPS.put("ube_cream_ube_cake",                        new String[]{"ube", "tooltip.createfood.ube_cream_frosting_ingredient"});

        // waffles
        TIPS.put("butterscotch_chip_waffle",    new String[]{null, "tooltip.createfood.butterscotch_chips_ingredient"});
        TIPS.put("caramel_chip_waffle",         new String[]{null, "tooltip.createfood.caramel_chips_ingredient"});
        TIPS.put("chocolate_chip_waffle",       new String[]{null, "tooltip.createfood.chocolate_chips_ingredient"});
        TIPS.put("dark_chocolate_chip_waffle",  new String[]{null, "tooltip.createfood.dark_chocolate_chips_ingredient"});
        TIPS.put("toffee_chip_waffle",          new String[]{null, "tooltip.createfood.toffee_chips_ingredient"});
        TIPS.put("white_chocolate_chip_waffle", new String[]{null, "tooltip.createfood.white_chocolate_chips_ingredient"});

        // cooked pizzas
        TIPS.put("bacon_pizza",           new String[]{null, "tooltip.createfood.bacon_ingredient"});
        TIPS.put("cheese_pizza",          new String[]{null, "tooltip.createfood.cheese_ingredient"});
        TIPS.put("fish_pizza",            new String[]{null, "tooltip.createfood.fish_ingredient"});
        TIPS.put("fish_bacon_pizza",      new String[]{null, "tooltip.createfood.fish_ingredient", "tooltip.createfood.bacon_ingredient"});
        TIPS.put("fish_onion_pizza",      new String[]{null, "tooltip.createfood.fish_ingredient", "tooltip.createfood.onion_ingredient"});
        TIPS.put("mushroom_pizza",        new String[]{null, "tooltip.createfood.mushroom_ingredient"});
        TIPS.put("mushroom_bacon_pizza",  new String[]{null, "tooltip.createfood.mushroom_ingredient", "tooltip.createfood.bacon_ingredient"});
        TIPS.put("mushroom_fish_pizza",   new String[]{null, "tooltip.createfood.mushroom_ingredient", "tooltip.createfood.fish_ingredient"});
        TIPS.put("mushroom_onion_pizza",  new String[]{null, "tooltip.createfood.mushroom_ingredient", "tooltip.createfood.onion_ingredient"});
        TIPS.put("onion_pizza",           new String[]{null, "tooltip.createfood.onion_ingredient"});
        TIPS.put("onion_bacon_pizza",     new String[]{null, "tooltip.createfood.onion_ingredient", "tooltip.createfood.bacon_ingredient"});
        TIPS.put("sausage_pizza",         new String[]{null, "tooltip.createfood.sausage_ingredient"});
        TIPS.put("sausage_bacon_pizza",   new String[]{null, "tooltip.createfood.sausage_ingredient", "tooltip.createfood.bacon_ingredient"});
        TIPS.put("sausage_fish_pizza",    new String[]{null, "tooltip.createfood.sausage_ingredient", "tooltip.createfood.fish_ingredient"});
        TIPS.put("sausage_mushroom_pizza",new String[]{null, "tooltip.createfood.sausage_ingredient", "tooltip.createfood.mushroom_ingredient"});
        TIPS.put("sausage_onion_pizza",   new String[]{null, "tooltip.createfood.sausage_ingredient", "tooltip.createfood.onion_ingredient"});

        // raw pizzas (with ingredients)
        TIPS.put("pizza_dough_tomato_sauce",        new String[]{null, "tooltip.createfood.tomato_sauce_ingredient"});
        TIPS.put("raw_bacon_pizza",                 new String[]{null, "tooltip.createfood.bacon_ingredient"});
        TIPS.put("raw_cheese_pizza",                new String[]{null, "tooltip.createfood.cheese_ingredient"});
        TIPS.put("raw_fish_pizza",                  new String[]{null, "tooltip.createfood.fish_ingredient"});
        TIPS.put("raw_fish_bacon_pizza",            new String[]{null, "tooltip.createfood.fish_ingredient", "tooltip.createfood.bacon_ingredient"});
        TIPS.put("raw_fish_onion_pizza",            new String[]{null, "tooltip.createfood.fish_ingredient", "tooltip.createfood.onion_ingredient"});
        TIPS.put("raw_mushroom_pizza",              new String[]{null, "tooltip.createfood.mushroom_ingredient"});
        TIPS.put("raw_mushroom_bacon_pizza",        new String[]{null, "tooltip.createfood.mushroom_ingredient", "tooltip.createfood.bacon_ingredient"});
        TIPS.put("raw_mushroom_fish_pizza",         new String[]{null, "tooltip.createfood.mushroom_ingredient", "tooltip.createfood.fish_ingredient"});
        TIPS.put("raw_mushroom_onion_pizza",        new String[]{null, "tooltip.createfood.mushroom_ingredient", "tooltip.createfood.onion_ingredient"});
        TIPS.put("raw_onion_pizza",                 new String[]{null, "tooltip.createfood.onion_ingredient"});
        TIPS.put("raw_onion_bacon_pizza",           new String[]{null, "tooltip.createfood.onion_ingredient", "tooltip.createfood.bacon_ingredient"});
        TIPS.put("raw_sausage_pizza",               new String[]{null, "tooltip.createfood.sausage_ingredient"});
        TIPS.put("raw_sausage_bacon_pizza",         new String[]{null, "tooltip.createfood.sausage_ingredient", "tooltip.createfood.bacon_ingredient"});
        TIPS.put("raw_sausage_fish_pizza",          new String[]{null, "tooltip.createfood.sausage_ingredient", "tooltip.createfood.fish_ingredient"});
        TIPS.put("raw_sausage_mushroom_pizza",      new String[]{null, "tooltip.createfood.sausage_ingredient", "tooltip.createfood.mushroom_ingredient"});
        TIPS.put("raw_sausage_onion_pizza",         new String[]{null, "tooltip.createfood.sausage_ingredient", "tooltip.createfood.onion_ingredient"});

        // pies with crust ingredients
        TIPS.put("chocolate_pie_graham_cracker",              new String[]{null, "tooltip.createfood.graham_cracker_pie_crust_ingredient"});
        TIPS.put("cream_pie_graham_cracker",                  new String[]{null, "tooltip.createfood.graham_cracker_pie_crust_ingredient"});
        TIPS.put("cream_pie_chocolate_graham_cracker",        new String[]{null, "tooltip.createfood.chocolate_graham_cracker_pie_crust_ingredient"});
        TIPS.put("raw_chocolate_pie_graham_cracker",          new String[]{null, "tooltip.createfood.graham_cracker_pie_crust_ingredient"});
        TIPS.put("raw_cream_pie_graham_cracker",              new String[]{null, "tooltip.createfood.graham_cracker_pie_crust_ingredient"});
        TIPS.put("raw_cream_pie_chocolate_graham_cracker",    new String[]{null, "tooltip.createfood.chocolate_graham_cracker_pie_crust_ingredient"});
    }
}
