package dev.averageanime.registry;

import dev.averageanime.registry.type.BlockEntry;

import static dev.averageanime.util.Tooltips.tips;

@SuppressWarnings("unused")
public final class BlockRegistry {

    private BlockRegistry() {}

    public static void init() {}

    public static final BlockEntry APPLE_CHEESECAKE = BlockEntry.cookedPie("apple_cheesecake", "apple_cheesecake_slice");
    public static final BlockEntry APPLE_CREAM_CAKE = BlockEntry.cake("apple_cream_cake", "apple_cream_cake_slice", tips(null, "apple_cream_frosting_ingredient"));
    public static final BlockEntry BACON_PIZZA = BlockEntry.cookedPizza("bacon_pizza", "bacon_pizza_slice", tips(null, "bacon_ingredient"));
    public static final BlockEntry BERRY_CREAM_CAKE = BlockEntry.cake("berry_cream_cake", "berry_cream_cake_slice", tips(null, "berry_cream_frosting_ingredient"));
    public static final BlockEntry BERRY_CREAM_CAKE_CHORUS_FRUIT = BlockEntry.cake("berry_cream_cake_chorus_fruit", "berry_cream_cake_slice_chorus_fruit", tips(null, "berry_cream_frosting_ingredient", "chorus_fruit_ingredient"));
    public static final BlockEntry BERRY_CREAM_CAKE_GLOW_BERRY = BlockEntry.cake("berry_cream_cake_glow_berry", "berry_cream_cake_slice_glow_berry", tips(null, "berry_cream_frosting_ingredient", "glow_berry_ingredient"));
    public static final BlockEntry BERRY_CREAM_CAKE_SWEET_BERRY = BlockEntry.cake("berry_cream_cake_sweet_berry", "berry_cream_cake_slice_sweet_berry", tips(null, "berry_cream_frosting_ingredient", "berry_ingredient"));
    public static final BlockEntry BERRY_PIE = BlockEntry.cookedPie("berry_pie", "berry_pie_slice");
    public static final BlockEntry BLACK_GELATIN_DESSERT_BLOCK_ENTRY = BlockEntry.gelatin("black_gelatin_dessert_block");
    public static final BlockEntry BLUE_GELATIN_DESSERT_BLOCK_ENTRY = BlockEntry.gelatin("blue_gelatin_dessert_block");
    public static final BlockEntry BROWN_GELATIN_DESSERT_BLOCK_ENTRY = BlockEntry.gelatin("brown_gelatin_dessert_block");
    public static final BlockEntry BUTTERSCOTCH_CHIP_WAFFLE = BlockEntry.waffle("butterscotch_chip_waffle", "butterscotch_chip_mini_waffle", tips(null, "butterscotch_chips_ingredient"));
    public static final BlockEntry CAKE_BASE = BlockEntry.cakeBase("cake_base");
    public static final BlockEntry CARAMEL_CHIP_WAFFLE = BlockEntry.waffle("caramel_chip_waffle", "caramel_chip_mini_waffle", tips(null, "caramel_chips_ingredient"));
    public static final BlockEntry CHEESECAKE = BlockEntry.cookedPie("cheesecake", "cheesecake_slice");
    public static final BlockEntry CHEESE_BLOCK_ENTRY = BlockEntry.cheese("cheese_block", "cheese_slice");
    public static final BlockEntry CHEESE_PIZZA = BlockEntry.cookedPizza("cheese_pizza", "cheese_pizza_slice", tips(null, "cheese_ingredient"));
    public static final BlockEntry CHOCOLATE_CAKE_BASE = BlockEntry.cakeBase("chocolate_cake_base");
    public static final BlockEntry CHOCOLATE_CHIP_WAFFLE = BlockEntry.waffle("chocolate_chip_waffle", "chocolate_chip_mini_waffle", tips(null, "chocolate_chips_ingredient"));
    public static final BlockEntry CHOCOLATE_CREAM_CAKE = BlockEntry.cake("chocolate_cream_cake", "chocolate_cream_cake_slice", tips(null, "chocolate_cream_frosting_ingredient"));
    public static final BlockEntry CHOCOLATE_CREAM_CAKE_BUTTERSCOTCH = BlockEntry.cake("chocolate_cream_cake_butterscotch", "chocolate_cream_cake_slice_butterscotch", tips(null, "chocolate_cream_frosting_ingredient", "butterscotch_chips_ingredient"));
    public static final BlockEntry CHOCOLATE_CREAM_CAKE_CARAMEL = BlockEntry.cake("chocolate_cream_cake_caramel", "chocolate_cream_cake_slice_caramel", tips(null, "chocolate_cream_frosting_ingredient", "caramel_chips_ingredient"));
    public static final BlockEntry CHOCOLATE_CREAM_CAKE_CHOCOLATE = BlockEntry.cake("chocolate_cream_cake_chocolate", "chocolate_cream_cake_slice_chocolate", tips(null, "chocolate_cream_frosting_ingredient", "chocolate_chips_ingredient"));
    public static final BlockEntry CHOCOLATE_CREAM_CAKE_DARK_CHOCOLATE = BlockEntry.cake("chocolate_cream_cake_dark_chocolate", "chocolate_cream_cake_slice_dark_chocolate", tips(null, "chocolate_cream_frosting_ingredient", "dark_chocolate_chips_ingredient"));
    public static final BlockEntry CHOCOLATE_CREAM_CAKE_TOFFEE = BlockEntry.cake("chocolate_cream_cake_toffee", "chocolate_cream_cake_slice_toffee", tips(null, "chocolate_cream_frosting_ingredient", "toffee_chips_ingredient"));
    public static final BlockEntry CHOCOLATE_CREAM_CAKE_WHITE_CHOCOLATE = BlockEntry.cake("chocolate_cream_cake_white_chocolate", "chocolate_cream_cake_slice_white_chocolate", tips(null, "chocolate_cream_frosting_ingredient", "white_chocolate_chips_ingredient"));
    public static final BlockEntry CHOCOLATE_CREAM_CHOCOLATE_CAKE = BlockEntry.cake("chocolate_cream_chocolate_cake", "chocolate_cream_chocolate_cake_slice", tips(null, "chocolate_cream_frosting_ingredient"));
    public static final BlockEntry CHOCOLATE_PIE_GRAHAM_CRACKER = BlockEntry.cookedPie("chocolate_pie_graham_cracker", "chocolate_pie_graham_cracker_slice", tips(null, "graham_cracker_pie_crust_ingredient"));
    public static final BlockEntry CHORUS_FRUIT_CHEESECAKE = BlockEntry.cookedPie("chorus_fruit_cheesecake", "chorus_fruit_cheesecake_slice");
    public static final BlockEntry CHORUS_FRUIT_CREAM_CAKE = BlockEntry.cake("chorus_fruit_cream_cake", "chorus_fruit_cream_cake_slice", tips(null, "chorus_fruit_cream_frosting_ingredient"));
    public static final BlockEntry CHORUS_FRUIT_CREAM_CAKE_CHORUS_FRUIT = BlockEntry.cake("chorus_fruit_cream_cake_chorus_fruit", "chorus_fruit_cream_cake_slice_chorus_fruit", tips(null, "chorus_fruit_cream_frosting_ingredient", "chorus_fruit_ingredient"));
    public static final BlockEntry CHORUS_FRUIT_CREAM_CAKE_GLOW_BERRY = BlockEntry.cake("chorus_fruit_cream_cake_glow_berry", "chorus_fruit_cream_cake_slice_glow_berry", tips(null, "chorus_fruit_cream_frosting_ingredient", "glow_berry_ingredient"));
    public static final BlockEntry CHORUS_FRUIT_CREAM_CAKE_SWEET_BERRY = BlockEntry.cake("chorus_fruit_cream_cake_sweet_berry", "chorus_fruit_cream_cake_slice_sweet_berry", tips(null, "chorus_fruit_cream_frosting_ingredient", "berry_ingredient"));
    public static final BlockEntry CHORUS_FRUIT_PIE = BlockEntry.cookedPie("chorus_fruit_pie", "chorus_fruit_pie_slice");
    public static final BlockEntry COOKIE_CREAM_PIE = BlockEntry.cookedPie("cookie_cream_pie", "cookie_cream_pie_slice");
    public static final BlockEntry CREAM_CAKE = BlockEntry.cake("cream_cake", "cream_cake_slice", tips(null, "cream_frosting_ingredient"));
    public static final BlockEntry CREAM_CAKE_CHORUS_FRUIT = BlockEntry.cake("cream_cake_chorus_fruit", "cream_cake_slice_chorus_fruit", tips(null, "cream_frosting_ingredient", "chorus_fruit_ingredient"));
    public static final BlockEntry CREAM_CAKE_GLOW_BERRY = BlockEntry.cake("cream_cake_glow_berry", "cream_cake_slice_glow_berry", tips(null, "cream_frosting_ingredient", "glow_berry_ingredient"));
    public static final BlockEntry CREAM_CHOCOLATE_CAKE = BlockEntry.cake("cream_chocolate_cake", "cream_chocolate_cake_slice", tips(null, "cream_frosting_ingredient"));
    public static final BlockEntry CREAM_PIE_CHOCOLATE_GRAHAM_CRACKER = BlockEntry.cookedPie("cream_pie_chocolate_graham_cracker", "cream_pie_chocolate_graham_cracker_slice", tips(null, "chocolate_graham_cracker_pie_crust_ingredient"));
    public static final BlockEntry CREAM_PIE_GRAHAM_CRACKER = BlockEntry.cookedPie("cream_pie_graham_cracker", "cream_pie_graham_cracker_slice", tips(null, "graham_cracker_pie_crust_ingredient"));
    public static final BlockEntry CYAN_GELATIN_DESSERT_BLOCK_ENTRY = BlockEntry.gelatin("cyan_gelatin_dessert_block");
    public static final BlockEntry DARK_CHOCOLATE_CHIP_WAFFLE = BlockEntry.waffle("dark_chocolate_chip_waffle", "dark_chocolate_chip_mini_waffle", tips(null, "dark_chocolate_chips_ingredient"));
    public static final BlockEntry FISH_BACON_PIZZA = BlockEntry.cookedPizza("fish_bacon_pizza", "fish_bacon_pizza_slice", tips(null, "fish_ingredient", "bacon_ingredient"));
    public static final BlockEntry FISH_ONION_PIZZA = BlockEntry.cookedPizza("fish_onion_pizza", "fish_onion_pizza_slice", tips(null, "fish_ingredient", "onion_ingredient"));
    public static final BlockEntry FISH_PIZZA = BlockEntry.cookedPizza("fish_pizza", "fish_pizza_slice", tips(null, "fish_ingredient"));
    public static final BlockEntry GELATIN_DESSERT_BLOCK_ENTRY = BlockEntry.gelatin("gelatin_dessert_block");
    public static final BlockEntry GLOW_BERRY_CHEESECAKE = BlockEntry.cookedPie("glow_berry_cheesecake", "glow_berry_cheesecake_slice");
    public static final BlockEntry GLOW_BERRY_CREAM_CAKE = BlockEntry.cake("glow_berry_cream_cake", "glow_berry_cream_cake_slice", tips(null, "glow_berry_cream_frosting_ingredient"));
    public static final BlockEntry GLOW_BERRY_CREAM_CAKE_CHORUS_FRUIT = BlockEntry.cake("glow_berry_cream_cake_chorus_fruit", "glow_berry_cream_cake_slice_chorus_fruit", tips(null, "glow_berry_cream_frosting_ingredient", "chorus_fruit_ingredient"));
    public static final BlockEntry GLOW_BERRY_CREAM_CAKE_GLOW_BERRY = BlockEntry.cake("glow_berry_cream_cake_glow_berry", "glow_berry_cream_cake_slice_glow_berry", tips(null, "glow_berry_cream_frosting_ingredient", "glow_berry_ingredient"));
    public static final BlockEntry GLOW_BERRY_CREAM_CAKE_SWEET_BERRY = BlockEntry.cake("glow_berry_cream_cake_sweet_berry", "glow_berry_cream_cake_slice_sweet_berry", tips(null, "glow_berry_cream_frosting_ingredient", "berry_ingredient"));
    public static final BlockEntry GLOW_BERRY_PIE = BlockEntry.cookedPie("glow_berry_pie", "glow_berry_pie_slice");
    public static final BlockEntry GRAY_GELATIN_DESSERT_BLOCK_ENTRY = BlockEntry.gelatin("gray_gelatin_dessert_block");
    public static final BlockEntry GREEN_GELATIN_DESSERT_BLOCK_ENTRY = BlockEntry.gelatin("green_gelatin_dessert_block");
    public static final BlockEntry GYRO_MEAT_BLOCK_ENTRY = BlockEntry.gyroMeat("gyro_meat_block", "gyro_meat_slice");
    public static final BlockEntry LIGHT_BLUE_GELATIN_DESSERT_BLOCK_ENTRY = BlockEntry.gelatin("light_blue_gelatin_dessert_block");
    public static final BlockEntry LIGHT_GRAY_GELATIN_DESSERT_BLOCK_ENTRY = BlockEntry.gelatin("light_gray_gelatin_dessert_block");
    public static final BlockEntry LIME_GELATIN_DESSERT_BLOCK_ENTRY = BlockEntry.gelatin("lime_gelatin_dessert_block");
    public static final BlockEntry MAGENTA_GELATIN_DESSERT_BLOCK_ENTRY = BlockEntry.gelatin("magenta_gelatin_dessert_block");
    public static final BlockEntry MEAT_PIE = BlockEntry.cookedPie("meat_pie", "meat_pie_slice");
    public static final BlockEntry MELON_CREAM_CAKE = BlockEntry.cake("melon_cream_cake", "melon_cream_cake_slice", tips(null, "melon_cream_frosting_ingredient"));
    public static final BlockEntry MUSHROOM_BACON_PIZZA = BlockEntry.cookedPizza("mushroom_bacon_pizza", "mushroom_bacon_pizza_slice", tips(null, "mushroom_ingredient", "bacon_ingredient"));
    public static final BlockEntry MUSHROOM_FISH_PIZZA = BlockEntry.cookedPizza("mushroom_fish_pizza", "mushroom_fish_pizza_slice", tips(null, "mushroom_ingredient", "fish_ingredient"));
    public static final BlockEntry MUSHROOM_ONION_PIZZA = BlockEntry.cookedPizza("mushroom_onion_pizza", "mushroom_onion_pizza_slice", tips(null, "mushroom_ingredient", "onion_ingredient"));
    public static final BlockEntry MUSHROOM_PIZZA = BlockEntry.cookedPizza("mushroom_pizza", "mushroom_pizza_slice", tips(null, "mushroom_ingredient"));
    public static final BlockEntry ONION_BACON_PIZZA = BlockEntry.cookedPizza("onion_bacon_pizza", "onion_bacon_pizza_slice", tips(null, "onion_ingredient", "bacon_ingredient"));
    public static final BlockEntry ONION_PIZZA = BlockEntry.cookedPizza("onion_pizza", "onion_pizza_slice", tips(null, "onion_ingredient"));
    public static final BlockEntry ORANGE_GELATIN_DESSERT_BLOCK_ENTRY = BlockEntry.gelatin("orange_gelatin_dessert_block");
    public static final BlockEntry PINK_GELATIN_DESSERT_BLOCK_ENTRY = BlockEntry.gelatin("pink_gelatin_dessert_block");
    public static final BlockEntry PIZZA_DOUGH = BlockEntry.rawPizza("pizza_dough");
    public static final BlockEntry PIZZA_DOUGH_TOMATO_SAUCE = BlockEntry.rawPizza("pizza_dough_tomato_sauce", tips(null, "tomato_sauce_ingredient"));
    public static final BlockEntry PUMPKIN_PIE_BLOCK_ENTRY = BlockEntry.cookedPie("pumpkin_pie_block", "pumpkin_pie_slice");
    public static final BlockEntry PURPLE_GELATIN_DESSERT_BLOCK_ENTRY = BlockEntry.gelatin("purple_gelatin_dessert_block");
    public static final BlockEntry RAW_APPLE_CHEESECAKE = BlockEntry.rawPie("raw_apple_cheesecake");
    public static final BlockEntry RAW_APPLE_PIE = BlockEntry.rawPie("raw_apple_pie");
    public static final BlockEntry RAW_BACON_PIZZA = BlockEntry.rawPizza("raw_bacon_pizza", tips(null, "bacon_ingredient"));
    public static final BlockEntry RAW_BERRY_CHEESECAKE = BlockEntry.rawPie("raw_berry_cheesecake");
    public static final BlockEntry RAW_BERRY_PIE = BlockEntry.rawPie("raw_berry_pie");
    public static final BlockEntry RAW_CHEESECAKE = BlockEntry.rawPie("raw_cheesecake");
    public static final BlockEntry RAW_CHEESE_PIZZA = BlockEntry.rawPizza("raw_cheese_pizza", tips(null, "cheese_ingredient"));
    public static final BlockEntry RAW_CHOCOLATE_GRAHAM_CRACKER_PIE_CRUST = BlockEntry.rawPie("raw_chocolate_graham_cracker_pie_crust");
    public static final BlockEntry RAW_CHOCOLATE_PIE = BlockEntry.rawPie("raw_chocolate_pie");
    public static final BlockEntry RAW_CHOCOLATE_PIE_GRAHAM_CRACKER = BlockEntry.rawPie("raw_chocolate_pie_graham_cracker", tips(null, "graham_cracker_pie_crust_ingredient"));
    public static final BlockEntry RAW_CHORUS_FRUIT_CHEESECAKE = BlockEntry.rawPie("raw_chorus_fruit_cheesecake");
    public static final BlockEntry RAW_CHORUS_FRUIT_PIE = BlockEntry.rawPie("raw_chorus_fruit_pie");
    public static final BlockEntry RAW_CREAM_PIE_CHOCOLATE_GRAHAM_CRACKER = BlockEntry.rawPie("raw_cream_pie_chocolate_graham_cracker", tips(null, "chocolate_graham_cracker_pie_crust_ingredient"));
    public static final BlockEntry RAW_CREAM_PIE_GRAHAM_CRACKER = BlockEntry.rawPie("raw_cream_pie_graham_cracker", tips(null, "graham_cracker_pie_crust_ingredient"));
    public static final BlockEntry RAW_FISH_BACON_PIZZA = BlockEntry.rawPizza("raw_fish_bacon_pizza", tips(null, "fish_ingredient", "bacon_ingredient"));
    public static final BlockEntry RAW_FISH_ONION_PIZZA = BlockEntry.rawPizza("raw_fish_onion_pizza", tips(null, "fish_ingredient", "onion_ingredient"));
    public static final BlockEntry RAW_FISH_PIZZA = BlockEntry.rawPizza("raw_fish_pizza", tips(null, "fish_ingredient"));
    public static final BlockEntry RAW_GLOW_BERRY_CHEESECAKE = BlockEntry.rawPie("raw_glow_berry_cheesecake");
    public static final BlockEntry RAW_GLOW_BERRY_PIE = BlockEntry.rawPie("raw_glow_berry_pie");
    public static final BlockEntry RAW_GRAHAM_CRACKER_PIE_CRUST = BlockEntry.rawPie("raw_graham_cracker_pie_crust");
    public static final BlockEntry RAW_MEAT_PIE = BlockEntry.rawPie("raw_meat_pie");
    public static final BlockEntry RAW_MUSHROOM_BACON_PIZZA = BlockEntry.rawPizza("raw_mushroom_bacon_pizza", tips(null, "mushroom_ingredient", "bacon_ingredient"));
    public static final BlockEntry RAW_MUSHROOM_FISH_PIZZA = BlockEntry.rawPizza("raw_mushroom_fish_pizza", tips(null, "mushroom_ingredient", "fish_ingredient"));
    public static final BlockEntry RAW_MUSHROOM_ONION_PIZZA = BlockEntry.rawPizza("raw_mushroom_onion_pizza", tips(null, "mushroom_ingredient", "onion_ingredient"));
    public static final BlockEntry RAW_MUSHROOM_PIZZA = BlockEntry.rawPizza("raw_mushroom_pizza", tips(null, "mushroom_ingredient"));
    public static final BlockEntry RAW_ONION_BACON_PIZZA = BlockEntry.rawPizza("raw_onion_bacon_pizza", tips(null, "onion_ingredient", "bacon_ingredient"));
    public static final BlockEntry RAW_ONION_PIZZA = BlockEntry.rawPizza("raw_onion_pizza", tips(null, "onion_ingredient"));
    public static final BlockEntry RAW_PIE_CRUST = BlockEntry.rawPie("raw_pie_crust");
    public static final BlockEntry RAW_PUMPKIN_PIE = BlockEntry.rawPie("raw_pumpkin_pie");
    public static final BlockEntry RAW_SAUSAGE_BACON_PIZZA = BlockEntry.rawPizza("raw_sausage_bacon_pizza", tips(null, "sausage_ingredient", "bacon_ingredient"));
    public static final BlockEntry RAW_SAUSAGE_FISH_PIZZA = BlockEntry.rawPizza("raw_sausage_fish_pizza", tips(null, "sausage_ingredient", "fish_ingredient"));
    public static final BlockEntry RAW_SAUSAGE_MUSHROOM_PIZZA = BlockEntry.rawPizza("raw_sausage_mushroom_pizza", tips(null, "sausage_ingredient", "mushroom_ingredient"));
    public static final BlockEntry RAW_SAUSAGE_ONION_PIZZA = BlockEntry.rawPizza("raw_sausage_onion_pizza", tips(null, "sausage_ingredient", "onion_ingredient"));
    public static final BlockEntry RAW_SAUSAGE_PIZZA = BlockEntry.rawPizza("raw_sausage_pizza", tips(null, "sausage_ingredient"));
    public static final BlockEntry RED_GELATIN_DESSERT_BLOCK_ENTRY = BlockEntry.gelatin("red_gelatin_dessert_block");
    public static final BlockEntry SAUSAGE_BACON_PIZZA = BlockEntry.cookedPizza("sausage_bacon_pizza", "sausage_bacon_pizza_slice", tips(null, "sausage_ingredient", "bacon_ingredient"));
    public static final BlockEntry SAUSAGE_FISH_PIZZA = BlockEntry.cookedPizza("sausage_fish_pizza", "sausage_fish_pizza_slice", tips(null, "sausage_ingredient", "fish_ingredient"));
    public static final BlockEntry SAUSAGE_MUSHROOM_PIZZA = BlockEntry.cookedPizza("sausage_mushroom_pizza", "sausage_mushroom_pizza_slice", tips(null, "sausage_ingredient", "mushroom_ingredient"));
    public static final BlockEntry SAUSAGE_ONION_PIZZA = BlockEntry.cookedPizza("sausage_onion_pizza", "sausage_onion_pizza_slice", tips(null, "sausage_ingredient", "onion_ingredient"));
    public static final BlockEntry SAUSAGE_PIZZA = BlockEntry.cookedPizza("sausage_pizza", "sausage_pizza_slice", tips(null, "sausage_ingredient"));
    public static final BlockEntry SMORES_PIE = BlockEntry.cookedPie("smores_pie", "smores_pie_slice");
    public static final BlockEntry TOFFEE_CHIP_WAFFLE = BlockEntry.waffle("toffee_chip_waffle", "toffee_chip_mini_waffle", tips(null, "toffee_chips_ingredient"));
    public static final BlockEntry UBE_CAKE_BASE = BlockEntry.cakeBase("ube_cake_base", tips("ube"));
    public static final BlockEntry UBE_CREAM_UBE_CAKE = BlockEntry.cake("ube_cream_ube_cake", "ube_cream_ube_cake_slice", tips("ube", "ube_cream_frosting_ingredient"));
    public static final BlockEntry WAFFLE = BlockEntry.waffle("waffle", "mini_waffle");
    public static final BlockEntry WHITE_CHOCOLATE_CHIP_WAFFLE = BlockEntry.waffle("white_chocolate_chip_waffle", "white_chocolate_chip_mini_waffle", tips(null, "white_chocolate_chips_ingredient"));
    public static final BlockEntry YELLOW_GELATIN_DESSERT_BLOCK_ENTRY = BlockEntry.gelatin("yellow_gelatin_dessert_block");
}