package dev.averageanime.registry;

import dev.averageanime.registry.type.FluidEntry;

import static dev.averageanime.registry.type.FluidEntry.fluid;

@SuppressWarnings("unused")
public final class FluidRegistry {
    private FluidRegistry() {}

    public static void init() {}

    public static final FluidEntry APPLE_CREAM_FROSTING_FLUID_ENTRY = fluid("apple_cream_frosting");
    public static final FluidEntry APPLE_CUSTARD_FLUID_ENTRY = fluid("apple_custard",              1, 4);
    public static final FluidEntry APPLE_ICE_CREAM_FLUID_ENTRY = fluid("apple_ice_cream");
    public static final FluidEntry APPLE_JAM_FLUID_ENTRY = fluid("apple_jam",                 2, 4);
    public static final FluidEntry APPLE_JUICE_FLUID_ENTRY = fluid("apple_juice",               3, 2);
    public static final FluidEntry APPLE_MILKSHAKE_FLUID_ENTRY = fluid("apple_milkshake",           2, 4);
    public static final FluidEntry APPLE_PIE_FILLING_FLUID_ENTRY = fluid("apple_pie_filling");
    public static final FluidEntry BERRY_CREAM_FROSTING_FLUID_ENTRY = fluid("berry_cream_frosting");
    public static final FluidEntry BERRY_CUSTARD_FLUID_ENTRY = fluid("berry_custard",             1, 4);
    public static final FluidEntry BERRY_ICE_CREAM_FLUID_ENTRY = fluid("berry_ice_cream");
    public static final FluidEntry BERRY_JAM_FLUID_ENTRY = fluid("berry_jam",                2, 4);
    public static final FluidEntry BERRY_JUICE_FLUID_ENTRY = fluid("berry_juice",              3, 2);
    public static final FluidEntry BERRY_MILKSHAKE_FLUID_ENTRY = fluid("berry_milkshake",          2, 4);
    public static final FluidEntry BERRY_PIE_FILLING_FLUID_ENTRY = fluid("berry_pie_filling");
    public static final FluidEntry BLACKSTRAP_MOLASSES_FLUID_ENTRY = fluid("blackstrap_molasses");
    public static final FluidEntry BLACK_GELATIN_MIX_FLUID_ENTRY = fluid("black_gelatin_mix");
    public static final FluidEntry BLUE_GELATIN_MIX_FLUID_ENTRY = fluid("blue_gelatin_mix");
    public static final FluidEntry BREAD_PUDDING_FLUID_ENTRY = fluid("bread_pudding");
    public static final FluidEntry BROWN_GELATIN_MIX_FLUID_ENTRY = fluid("brown_gelatin_mix");
    public static final FluidEntry BUTTERSCOTCH_FLUID_ENTRY = fluid("butterscotch");
    public static final FluidEntry BUTTERSCOTCH_FUDGE_FLUID_ENTRY = fluid("butterscotch_fudge");
    public static final FluidEntry CACAO_BUTTER_FLUID_ENTRY = fluid("cacao_butter");
    public static final FluidEntry CACAO_MASS_FLUID_ENTRY = fluid("cacao_mass");
    public static final FluidEntry CAKE_BATTER_FLUID_ENTRY = fluid("cake_batter",              2, 4);
    public static final FluidEntry CANE_SYRUP_FLUID_ENTRY = fluid("cane_syrup");
    public static final FluidEntry CARAMEL_FLUID_ENTRY = fluid("caramel");
    public static final FluidEntry CARAMEL_FUDGE_FLUID_ENTRY = fluid("caramel_fudge");
    public static final FluidEntry CHEESECAKE_FILLING_FLUID_ENTRY = fluid("cheesecake_filling");
    public static final FluidEntry CHOCOLATE_CAKE_BATTER_FLUID_ENTRY = fluid("chocolate_cake_batter",    2, 4);
    public static final FluidEntry CHOCOLATE_CREAM_FROSTING_FLUID_ENTRY = fluid("chocolate_cream_frosting");
    public static final FluidEntry CHOCOLATE_CUSTARD_FLUID_ENTRY = fluid("chocolate_custard",        1, 4);
    public static final FluidEntry CHOCOLATE_FUDGE_FLUID_ENTRY = fluid("chocolate_fudge");
    public static final FluidEntry CHOCOLATE_ICE_CREAM_FLUID_ENTRY = fluid("chocolate_ice_cream");
    public static final FluidEntry CHOCOLATE_MILKSHAKE_FLUID_ENTRY = fluid("chocolate_milkshake",      2, 4);
    public static final FluidEntry CHOCOLATE_MILK_FLUID_ENTRY = fluid("chocolate_milk");
    public static final FluidEntry CHORUS_FRUIT_CREAM_FROSTING_FLUID_ENTRY = fluid("chorus_fruit_cream_frosting");
    public static final FluidEntry CHORUS_FRUIT_CUSTARD_FLUID_ENTRY = fluid("chorus_fruit_custard",     1, 4);
    public static final FluidEntry CHORUS_FRUIT_ICE_CREAM_FLUID_ENTRY = fluid("chorus_fruit_ice_cream");
    public static final FluidEntry CHORUS_FRUIT_JAM_FLUID_ENTRY = fluid("chorus_fruit_jam",         2, 4);
    public static final FluidEntry CHORUS_FRUIT_JUICE_FLUID_ENTRY = fluid("chorus_fruit_juice",       3, 2);
    public static final FluidEntry CHORUS_FRUIT_MILKSHAKE_FLUID_ENTRY = fluid("chorus_fruit_milkshake",   2, 4);
    public static final FluidEntry CHORUS_FRUIT_PIE_FILLING_FLUID_ENTRY = fluid("chorus_fruit_pie_filling");
    public static final FluidEntry CONDENSED_MILK_FLUID_ENTRY = fluid("condensed_milk");
    public static final FluidEntry CREAM_CHEESE_FLUID_ENTRY = fluid("cream_cheese");
    public static final FluidEntry CREAM_FROSTING_FLUID_ENTRY = fluid("cream_frosting");
    public static final FluidEntry CREAM_PIE_FILLING_FLUID_ENTRY = fluid("cream_pie_filling");
    public static final FluidEntry CUSTARD_FLUID_ENTRY = fluid("custard",                  1, 4);
    public static final FluidEntry CYAN_GELATIN_MIX_FLUID_ENTRY = fluid("cyan_gelatin_mix");
    public static final FluidEntry DARK_CHOCOLATE_FLUID_ENTRY = fluid("dark_chocolate");
    public static final FluidEntry DARK_CHOCOLATE_FUDGE_FLUID_ENTRY = fluid("dark_chocolate_fudge");
    public static final FluidEntry EGG_FLUID_ENTRY = fluid("egg");
    public static final FluidEntry EGG_WHITES_FLUID_ENTRY = fluid("egg_whites");
    public static final FluidEntry FISH_CHOWDER_FLUID_ENTRY = fluid("fish_chowder");
    public static final FluidEntry FRUIT_SMOOTHIE_FLUID_ENTRY = fluid("fruit_smoothie");
    public static final FluidEntry GELATIN_MIX_FLUID_ENTRY = fluid("gelatin_mix");
    public static final FluidEntry GLOW_BERRY_CREAM_FROSTING_FLUID_ENTRY = fluid("glow_berry_cream_frosting");
    public static final FluidEntry GLOW_BERRY_ICE_CREAM_FLUID_ENTRY = fluid("glow_berry_ice_cream");
    public static final FluidEntry GLOW_BERRY_JAM_FLUID_ENTRY = fluid("glow_berry_jam",           2, 4);
    public static final FluidEntry GLOW_BERRY_JUICE_FLUID_ENTRY = fluid("glow_berry_juice",         3, 2);
    public static final FluidEntry GLOW_BERRY_MILKSHAKE_FLUID_ENTRY = fluid("glow_berry_milkshake",     2, 4);
    public static final FluidEntry GLOW_BERRY_PIE_FILLING_FLUID_ENTRY = fluid("glow_berry_pie_filling");
    public static final FluidEntry GRAY_GELATIN_MIX_FLUID_ENTRY = fluid("gray_gelatin_mix");
    public static final FluidEntry GREEN_GELATIN_MIX_FLUID_ENTRY = fluid("green_gelatin_mix");
    public static final FluidEntry HEAVY_CREAM_FLUID_ENTRY = fluid("heavy_cream");
    public static final FluidEntry HOT_CHOCOLATE_FLUID_ENTRY = fluid("hot_chocolate");
    public static final FluidEntry HOT_DARK_CHOCOLATE_FLUID_ENTRY = fluid("hot_dark_chocolate");
    public static final FluidEntry HOT_WHITE_CHOCOLATE_FLUID_ENTRY = fluid("hot_white_chocolate");
    public static final FluidEntry ICE_CREAM_FLUID_ENTRY = fluid("ice_cream");
    public static final FluidEntry KELP_SOUP_FLUID_ENTRY = fluid("kelp_soup");
    public static final FluidEntry LEATHER_SOUP_FLUID_ENTRY = fluid("leather_soup");
    public static final FluidEntry LIGHT_BLUE_GELATIN_MIX_FLUID_ENTRY = fluid("light_blue_gelatin_mix");
    public static final FluidEntry LIGHT_GRAY_GELATIN_MIX_FLUID_ENTRY = fluid("light_gray_gelatin_mix");
    public static final FluidEntry LIME_GELATIN_MIX_FLUID_ENTRY = fluid("lime_gelatin_mix");
    public static final FluidEntry LIQUID_CHEESE_FLUID_ENTRY = fluid("liquid_cheese");
    public static final FluidEntry MAGENTA_GELATIN_MIX_FLUID_ENTRY = fluid("magenta_gelatin_mix");
    public static final FluidEntry MELON_CREAM_FROSTING_FLUID_ENTRY = fluid("melon_cream_frosting");
    public static final FluidEntry MELON_CUSTARD_FLUID_ENTRY = fluid("melon_custard",            1, 4);
    public static final FluidEntry MELON_ICE_CREAM_FLUID_ENTRY = fluid("melon_ice_cream");
    public static final FluidEntry MELON_JAM_FLUID_ENTRY = fluid("melon_jam",               2, 4);
    public static final FluidEntry MELON_MILKSHAKE_FLUID_ENTRY = fluid("melon_milkshake",         2, 4);
    public static final FluidEntry MERINGUE_FLUID_ENTRY = fluid("meringue",                1, 4);
    public static final FluidEntry MILKSHAKE_FLUID_ENTRY = fluid("milkshake",               2, 4);
    public static final FluidEntry MOLASSES_FLUID_ENTRY = fluid("molasses");
    public static final FluidEntry MUFFIN_BATTER_FLUID_ENTRY = fluid("muffin_batter",           2, 4);
    public static final FluidEntry MUSHROOM_CREAM_SOUP_FLUID_ENTRY = fluid("mushroom_cream_soup");
    public static final FluidEntry MUTTON_STEW_FLUID_ENTRY = fluid("mutton_stew");
    public static final FluidEntry ORANGE_GELATIN_MIX_FLUID_ENTRY = fluid("orange_gelatin_mix");
    public static final FluidEntry PINK_GELATIN_MIX_FLUID_ENTRY = fluid("pink_gelatin_mix");
    public static final FluidEntry PORK_STEW_FLUID_ENTRY = fluid("pork_stew");
    public static final FluidEntry POTATO_CREAM_SOUP_FLUID_ENTRY = fluid("potato_cream_soup");
    public static final FluidEntry PUMPKIN_CUSTARD_FLUID_ENTRY = fluid("pumpkin_custard",         1, 4);
    public static final FluidEntry PUMPKIN_PIE_FILLING_FLUID_ENTRY = fluid("pumpkin_pie_filling");
    public static final FluidEntry PUMPKIN_PUREE_FLUID_ENTRY = fluid("pumpkin_puree");
    public static final FluidEntry PURPLE_GELATIN_MIX_FLUID_ENTRY = fluid("purple_gelatin_mix");
    public static final FluidEntry RED_GELATIN_MIX_FLUID_ENTRY = fluid("red_gelatin_mix");
    public static final FluidEntry RICE_PUDDING_FLUID_ENTRY = fluid("rice_pudding");
    public static final FluidEntry SHAKSHUKA_FLUID_ENTRY = fluid("shakshuka");
    public static final FluidEntry SLIME_FLUID_ENTRY = fluid("slime");
    public static final FluidEntry SOUR_CREAM_FLUID_ENTRY = fluid("sour_cream");
    public static final FluidEntry SQUID_INK_FLUID_ENTRY = fluid("squid_ink");
    public static final FluidEntry SUGAR_CANE_JUICE_FLUID_ENTRY = fluid("sugar_cane_juice",        3, 2);
    public static final FluidEntry TACO_SAUCE_FLUID_ENTRY = fluid("taco_sauce",              2, 4);
    public static final FluidEntry TOFFEE_FLUID_ENTRY = fluid("toffee");
    public static final FluidEntry TOFFEE_FUDGE_FLUID_ENTRY = fluid("toffee_fudge");
    public static final FluidEntry TOMATO_CREAM_SOUP_FLUID_ENTRY = fluid("tomato_cream_soup");
    public static final FluidEntry VEGETABLE_OIL_FLUID_ENTRY = fluid("vegetable_oil");
    public static final FluidEntry VINEGAR_FLUID_ENTRY = fluid("vinegar");
    public static final FluidEntry WAFFLE_BATTER_FLUID_ENTRY = fluid("waffle_batter");
    public static final FluidEntry WHITE_CHOCOLATE_FLUID_ENTRY = fluid("white_chocolate");
    public static final FluidEntry WHITE_CHOCOLATE_FUDGE_FLUID_ENTRY = fluid("white_chocolate_fudge");
    public static final FluidEntry YELLOW_GELATIN_MIX_FLUID_ENTRY = fluid("yellow_gelatin_mix");
    public static final FluidEntry YOGURT_FLUID_ENTRY = fluid("yogurt");
}