package dev.averageanime.registry;

import dev.averageanime.registry.type.Fluid;

import static dev.averageanime.registry.type.Fluid.fluid;

@SuppressWarnings("unused")
public final class FluidRegistry {
    private FluidRegistry() {}

    /** Triggers class initialization (JLS §12.4.1). */
    public static void init() {}

    public static final Fluid APPLE_CREAM_FROSTING_FLUID       = fluid("apple_cream_frosting");
    public static final Fluid APPLE_CUSTARD_FLUID              = fluid("apple_custard",              1, 4);
    public static final Fluid APPLE_ICE_CREAM_FLUID            = fluid("apple_ice_cream");
    public static final Fluid APPLE_JAM_FLUID                  = fluid("apple_jam",                 2, 4);
    public static final Fluid APPLE_JUICE_FLUID                = fluid("apple_juice",               3, 2);
    public static final Fluid APPLE_MILKSHAKE_FLUID            = fluid("apple_milkshake",           2, 4);
    public static final Fluid APPLE_PIE_FILLING_FLUID          = fluid("apple_pie_filling");
    public static final Fluid BERRY_CREAM_FROSTING_FLUID       = fluid("berry_cream_frosting");
    public static final Fluid BERRY_CUSTARD_FLUID              = fluid("berry_custard",             1, 4);
    public static final Fluid BERRY_ICE_CREAM_FLUID            = fluid("berry_ice_cream");
    public static final Fluid BERRY_JAM_FLUID                  = fluid("berry_jam",                2, 4);
    public static final Fluid BERRY_JUICE_FLUID                = fluid("berry_juice",              3, 2);
    public static final Fluid BERRY_MILKSHAKE_FLUID            = fluid("berry_milkshake",          2, 4);
    public static final Fluid BERRY_PIE_FILLING_FLUID          = fluid("berry_pie_filling");
    public static final Fluid BLACKSTRAP_MOLASSES_FLUID        = fluid("blackstrap_molasses");
    public static final Fluid BLACK_GELATIN_MIX_FLUID          = fluid("black_gelatin_mix");
    public static final Fluid BLUE_GELATIN_MIX_FLUID           = fluid("blue_gelatin_mix");
    public static final Fluid BREAD_PUDDING_FLUID              = fluid("bread_pudding");
    public static final Fluid BROWN_GELATIN_MIX_FLUID          = fluid("brown_gelatin_mix");
    public static final Fluid BUTTERSCOTCH_FLUID               = fluid("butterscotch");
    public static final Fluid BUTTERSCOTCH_FUDGE_FLUID         = fluid("butterscotch_fudge");
    public static final Fluid CACAO_BUTTER_FLUID               = fluid("cacao_butter");
    public static final Fluid CACAO_MASS_FLUID                 = fluid("cacao_mass");
    public static final Fluid CAKE_BATTER_FLUID                = fluid("cake_batter",              2, 4);
    public static final Fluid CANE_SYRUP_FLUID                 = fluid("cane_syrup");
    public static final Fluid CARAMEL_FLUID                    = fluid("caramel");
    public static final Fluid CARAMEL_FUDGE_FLUID              = fluid("caramel_fudge");
    public static final Fluid CHEESECAKE_FILLING_FLUID         = fluid("cheesecake_filling");
    public static final Fluid CHOCOLATE_CAKE_BATTER_FLUID      = fluid("chocolate_cake_batter",    2, 4);
    public static final Fluid CHOCOLATE_CREAM_FROSTING_FLUID   = fluid("chocolate_cream_frosting");
    public static final Fluid CHOCOLATE_CUSTARD_FLUID          = fluid("chocolate_custard",        1, 4);
    public static final Fluid CHOCOLATE_FUDGE_FLUID            = fluid("chocolate_fudge");
    public static final Fluid CHOCOLATE_ICE_CREAM_FLUID        = fluid("chocolate_ice_cream");
    public static final Fluid CHOCOLATE_MILKSHAKE_FLUID        = fluid("chocolate_milkshake",      2, 4);
    public static final Fluid CHOCOLATE_MILK_FLUID             = fluid("chocolate_milk");
    public static final Fluid CHORUS_FRUIT_CREAM_FROSTING_FLUID = fluid("chorus_fruit_cream_frosting");
    public static final Fluid CHORUS_FRUIT_CUSTARD_FLUID       = fluid("chorus_fruit_custard",     1, 4);
    public static final Fluid CHORUS_FRUIT_ICE_CREAM_FLUID     = fluid("chorus_fruit_ice_cream");
    public static final Fluid CHORUS_FRUIT_JAM_FLUID           = fluid("chorus_fruit_jam",         2, 4);
    public static final Fluid CHORUS_FRUIT_JUICE_FLUID         = fluid("chorus_fruit_juice",       3, 2);
    public static final Fluid CHORUS_FRUIT_MILKSHAKE_FLUID     = fluid("chorus_fruit_milkshake",   2, 4);
    public static final Fluid CHORUS_FRUIT_PIE_FILLING_FLUID   = fluid("chorus_fruit_pie_filling");
    public static final Fluid COFFEE_TOFFEE_FLUID              = fluid("coffee_toffee");
    public static final Fluid COFFEE_TOFFEE_FUDGE_FLUID        = fluid("coffee_toffee_fudge");
    public static final Fluid CONDENSED_MILK_FLUID             = fluid("condensed_milk");
    public static final Fluid CREAM_CHEESE_FLUID               = fluid("cream_cheese");
    public static final Fluid CREAM_FROSTING_FLUID             = fluid("cream_frosting");
    public static final Fluid CREAM_PIE_FILLING_FLUID          = fluid("cream_pie_filling");
    public static final Fluid CUSTARD_FLUID                    = fluid("custard",                  1, 4);
    public static final Fluid CYAN_GELATIN_MIX_FLUID           = fluid("cyan_gelatin_mix");
    public static final Fluid DARK_CHOCOLATE_FLUID             = fluid("dark_chocolate");
    public static final Fluid DARK_CHOCOLATE_FUDGE_FLUID       = fluid("dark_chocolate_fudge");
    public static final Fluid EGG_FLUID                        = fluid("egg");
    public static final Fluid EGG_WHITES_FLUID                 = fluid("egg_whites");
    public static final Fluid FISH_CHOWDER_FLUID               = fluid("fish_chowder");
    public static final Fluid FRUIT_SMOOTHIE_FLUID             = fluid("fruit_smoothie");
    public static final Fluid GELATIN_MIX_FLUID                = fluid("gelatin_mix");
    public static final Fluid GLOW_BERRY_CREAM_FROSTING_FLUID  = fluid("glow_berry_cream_frosting");
    public static final Fluid GLOW_BERRY_ICE_CREAM_FLUID       = fluid("glow_berry_ice_cream");
    public static final Fluid GLOW_BERRY_JAM_FLUID             = fluid("glow_berry_jam",           2, 4);
    public static final Fluid GLOW_BERRY_JUICE_FLUID           = fluid("glow_berry_juice",         3, 2);
    public static final Fluid GLOW_BERRY_MILKSHAKE_FLUID       = fluid("glow_berry_milkshake",     2, 4);
    public static final Fluid GLOW_BERRY_PIE_FILLING_FLUID     = fluid("glow_berry_pie_filling");
    public static final Fluid GRAY_GELATIN_MIX_FLUID           = fluid("gray_gelatin_mix");
    public static final Fluid GREEN_GELATIN_MIX_FLUID          = fluid("green_gelatin_mix");
    public static final Fluid HEAVY_CREAM_FLUID                = fluid("heavy_cream");
    public static final Fluid HOT_CHOCOLATE_FLUID              = fluid("hot_chocolate");
    public static final Fluid HOT_DARK_CHOCOLATE_FLUID         = fluid("hot_dark_chocolate");
    public static final Fluid HOT_WHITE_CHOCOLATE_FLUID        = fluid("hot_white_chocolate");
    public static final Fluid ICE_CREAM_FLUID                  = fluid("ice_cream");
    public static final Fluid KELP_SOUP_FLUID                  = fluid("kelp_soup");
    public static final Fluid LEATHER_SOUP_FLUID               = fluid("leather_soup");
    public static final Fluid LIGHT_BLUE_GELATIN_MIX_FLUID     = fluid("light_blue_gelatin_mix");
    public static final Fluid LIGHT_GRAY_GELATIN_MIX_FLUID     = fluid("light_gray_gelatin_mix");
    public static final Fluid LIME_GELATIN_MIX_FLUID           = fluid("lime_gelatin_mix");
    public static final Fluid LIQUID_CHEESE_FLUID              = fluid("liquid_cheese");
    public static final Fluid MAGENTA_GELATIN_MIX_FLUID        = fluid("magenta_gelatin_mix");
    public static final Fluid MELON_CREAM_FROSTING_FLUID       = fluid("melon_cream_frosting");
    public static final Fluid MELON_CUSTARD_FLUID              = fluid("melon_custard",            1, 4);
    public static final Fluid MELON_ICE_CREAM_FLUID            = fluid("melon_ice_cream");
    public static final Fluid MELON_JAM_FLUID                  = fluid("melon_jam",               2, 4);
    public static final Fluid MELON_MILKSHAKE_FLUID            = fluid("melon_milkshake",         2, 4);
    public static final Fluid MERINGUE_FLUID                   = fluid("meringue",                1, 4);
    public static final Fluid MILKSHAKE_FLUID                  = fluid("milkshake",               2, 4);
    public static final Fluid MOLASSES_FLUID                   = fluid("molasses");
    public static final Fluid MUFFIN_BATTER_FLUID              = fluid("muffin_batter",           2, 4);
    public static final Fluid MUSHROOM_CREAM_SOUP_FLUID        = fluid("mushroom_cream_soup");
    public static final Fluid MUTTON_STEW_FLUID                = fluid("mutton_stew");
    public static final Fluid ORANGE_GELATIN_MIX_FLUID         = fluid("orange_gelatin_mix");
    public static final Fluid PINK_GELATIN_MIX_FLUID           = fluid("pink_gelatin_mix");
    public static final Fluid PORK_STEW_FLUID                  = fluid("pork_stew");
    public static final Fluid POTATO_CREAM_SOUP_FLUID          = fluid("potato_cream_soup");
    public static final Fluid PUMPKIN_CUSTARD_FLUID            = fluid("pumpkin_custard",         1, 4);
    public static final Fluid PUMPKIN_PIE_FILLING_FLUID        = fluid("pumpkin_pie_filling");
    public static final Fluid PUMPKIN_PUREE_FLUID              = fluid("pumpkin_puree");
    public static final Fluid PURPLE_GELATIN_MIX_FLUID         = fluid("purple_gelatin_mix");
    public static final Fluid RED_GELATIN_MIX_FLUID            = fluid("red_gelatin_mix");
    public static final Fluid RICE_PUDDING_FLUID               = fluid("rice_pudding");
    public static final Fluid SLIME_FLUID                      = fluid("slime");
    public static final Fluid SOUR_CREAM_FLUID                 = fluid("sour_cream");
    public static final Fluid SQUID_INK_FLUID                  = fluid("squid_ink");
    public static final Fluid SUGAR_CANE_JUICE_FLUID           = fluid("sugar_cane_juice",        3, 2);
    public static final Fluid TACO_SAUCE_FLUID                 = fluid("taco_sauce",              2, 4);
    public static final Fluid TOFFEE_FLUID                     = fluid("toffee");
    public static final Fluid TOFFEE_FUDGE_FLUID               = fluid("toffee_fudge");
    public static final Fluid TOMATO_CREAM_SOUP_FLUID          = fluid("tomato_cream_soup");
    public static final Fluid UBE_CAKE_BATTER_FLUID            = fluid("ube_cake_batter",         2, 4);
    public static final Fluid UBE_CREAM_FROSTING_FLUID         = fluid("ube_cream_frosting");
    public static final Fluid VEGETABLE_OIL_FLUID              = fluid("vegetable_oil");
    public static final Fluid VINEGAR_FLUID                    = fluid("vinegar");
    public static final Fluid WAFFLE_BATTER_FLUID              = fluid("waffle_batter");
    public static final Fluid WHITE_CHOCOLATE_FLUID            = fluid("white_chocolate");
    public static final Fluid WHITE_CHOCOLATE_FUDGE_FLUID      = fluid("white_chocolate_fudge");
    public static final Fluid YELLOW_GELATIN_MIX_FLUID         = fluid("yellow_gelatin_mix");
    public static final Fluid YOGURT_FLUID                     = fluid("yogurt");
}
