package dev.averageanime.neoforge.datagen.provider;

import dev.averageanime.CreateFoodCommon;
import dev.averageanime.config.AddonManifest;
import net.minecraft.data.CachedOutput;
import net.minecraft.data.DataProvider;
import net.minecraft.data.PackOutput;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.concurrent.CompletableFuture;

/** Writes the registry names an addon owns; emitted outside the pack tree so it never ships in a jar. */
public class AddonManifestProvider implements DataProvider {

    private static final String FILE_NAME = "addon-manifest.txt";

    private final PackOutput output;

    public AddonManifestProvider(PackOutput output) {
        this.output = output;
    }

    @Override
    public CompletableFuture<?> run(CachedOutput cache) {
        return CompletableFuture.runAsync(() -> {
            Set<String> names = AddonManifest.names();
            List<String> lines = new ArrayList<>();
            lines.add("# Registry names owned by an addon, not by the base mod.");
            lines.add("# Generated by AddonManifestProvider.");
            lines.add("# count: " + names.size());
            lines.addAll(names);

            Path target = output.getOutputFolder().resolve("../" + FILE_NAME).normalize();
            try {
                Files.createDirectories(target.getParent());
                Files.writeString(target, String.join("\n", lines) + "\n", StandardCharsets.UTF_8);
            } catch (IOException e) {
                throw new IllegalStateException("Failed to write " + FILE_NAME, e);
            }
        });
    }

    @Override
    public String getName() {
        return CreateFoodCommon.MOD_ID + " addon manifest";
    }
}
