plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

def commonResources = rootProject.project(':common').projectDir.toPath()
        .resolve('src/main/resources').toFile().absolutePath

neoForge {
    version = neoforge_version
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
        }
        data {
            data()
            programArguments.addAll '--mod', mod_id, '--all',
                    '--output', file('src/generated/resources/').getAbsolutePath(),
                    '--existing', file('src/main/resources/').getAbsolutePath(),
                    '--existing', commonResources
        }
        server {
            server()
            setGameDirectory(file('server'))
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
    repositories {
        // CurseMaven
        exclusiveContent {
            forRepository {
                maven {
                    url "https://cursemaven.com"
                }
            }
            filter {
                includeGroup "curse.maven"
            }
        }
        maven { url = "https://maven.createmod.net" } // Create, Ponder, Flywheel
        maven { url = "https://maven.ithundxr.dev/snapshots" } // Registrate
        maven { url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/" } // ForgeConfigAPIPort
    }

    dependencies {
        //implementation("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") { transitive = false }
        //implementation("net.createmod.ponder:Ponder-NeoForge-${minecraft_version}:${ponder_version}")
        //compileOnly("dev.engine-room.flywheel:flywheel-neoforge-api-${minecraft_version}:${flywheel_version}")
        //runtimeOnly("dev.engine-room.flywheel:flywheel-neoforge-${minecraft_version}:${flywheel_version}")
        //implementation("com.tterrag.registrate:Registrate:${registrate_version}")

        compileOnly "curse.maven:farmers-delight-398521:5566383"

    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

tasks.register('liteJar', Jar) {
    archiveClassifier = 'lite'

    from sourceSets.main.output

    exclude '**/block/type/display/**'
    exclude '**/block/ModDisplayBlocks.class'
    exclude '**/tab/ModDisplayTabs.class'

    exclude '**/blockstates/*_plate_block.json'
    exclude '**/blockstates/plate_block.json'
    exclude '**/blockstates/small_plate_block.json'
    exclude '**/models/item/*_plate_block.json'
    exclude '**/models/item/*_bottle_block.json'
    exclude '**/models/item/*_bowl_block.json'
    exclude '**/models/block/*_plate_block.json'
    exclude '**/models/block/*_bottle_block.json'
    exclude '**/models/block/*_bowl_block.json'
    exclude '**/models/block/*_plate_block_1.json'
    exclude '**/models/block/*_plate_block_2.json'
    exclude '**/models/block/*_plate_block_3.json'
    exclude '**/models/block/*_plate_block_4.json'
    exclude '**/models/block/*_plate_block_5.json'
    exclude '**/models/block/*_plate_block_6.json'
    exclude '**/models/block/*_plate_block_7.json'
    exclude '**/models/block/*_plate_block_8.json'
    exclude '**/models/block/*_plate_block_9.json'
    exclude '**/models/block/plate_block.json'
    exclude '**/models/block/small_plate_block.json'
    exclude '**/loot_table/blocks/*_plate_block.json'
    exclude '**/loot_table/blocks/plate_block.json'
    exclude '**/loot_table/blocks/small_plate_block.json'
}

tasks.named('processResources') {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

build.dependsOn liteJar